"use client"

import type React from "react"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { ArrowRight, HelpCircle, ChevronsUpDown, Check } from "lucide-react"
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import { cn } from "@/lib/utils"

interface DailyRandomData {
  date: string;
  Question: {
    id: number;
    answer_id: number;
    artista: string;
    nombre: string;
    sampling_url: string;
    urlYT: string;
  };
  Answer: {
    id: number;
    song_title: string;
    artist_name: string;
    urlYT?: string;
  };
}

interface VinylHeroProps {
  title?: string;
  titleColor?: string;
  showInput?: boolean;
  linkText?: string;
  linkUrl?: string;
  videoId?: string | null;
  data?: DailyRandomData;
}

const availableSongs = [
  { value: "the-fairy-tale-biosphere", label: "The Fairy Tale - Biosphere" },
  { value: "vertical-pig-the-future-sound-of-london", label: "Vertical Pig - The Future Sound Of London" },
  { value: "polygon-window-the-dice-man", label: "Polygon Window - The Dice Man" },
  { value: "india-rubber-radiohead", label: "India Rubber - Radiohead" },
  { value: "yes-i-am-radiohead", label: "Yes I Am - Radiohead" },
  { value: "there-there-radiohead", label: "There, There - Radiohead" },
  { value: "new-town-velocity-johnny-marr", label: "New Town Velocity - Johnny Marr" },
  { value: "valentines-day-david-bowie", label: "Valentine's Day - David Bowie" },
  { value: "my-desire-interpol", label: "My Desire - Interpol" },
  { value: "liars-love-title-fight", label: "Liar's Love - Title Fight" },
  { value: "lift-radiohead", label: "Lift - Radiohead" },
  { value: "30-aos-conociendo-rusia", label: "30 Años - Conociendo Rusia" },
  { value: "nuevo-comienzo-usted-sealemelo", label: "Nuevo Comienzo - Usted Señalemelo" },
  { value: "dicen-que-va-a-parar-ryan", label: "Dicen Que Va a Parar - RYAN" },
  { value: "el-magnetismo-el-mat-a-un-polica-motorizado", label: "El Magnetismo - El Mató a un Policía Motorizado" },
  { value: "big-bang-usted-sealemelo", label: "Big Bang - Usted Señalemelo" },
  { value: "maana-usted-sealemelo", label: "Mañana - Usted Señalemelo" },
  { value: "las-voces-el-zar", label: "Las Voces - El Zar" },
  { value: "huracanes-los-espiritus", label: "Huracanes - Los Espiritus" },
  { value: "salir-del-confort-fonso", label: "Salir del Confort - Fonso" },
  { value: "plastilina-usted-sealemelo", label: "Plastilina - Usted Señalemelo" },
  { value: "textos-usted-sealemelo", label: "Textos - Usted Señalemelo" },
  { value: "time-fate-love-luca-prodan", label: "Time Fate Love - Luca Prodan" },
  { value: "luna-roja---remasterizado-2007-soda-stereo", label: "Luna Roja - Remasterizado 2007 - Soda Stereo" },
  { value: "conversacin-triple---remastered-don-cornelio-y-la-zona", label: "Conversación Triple - Remastered - Don Cornelio Y La Zona" },
  { value: "camalen---remasterizado-2007-soda-stereo", label: "Camaleón - Remasterizado 2007 - Soda Stereo" },
  { value: "lament-luca-prodan", label: "Lament - Luca Prodan" },
  { value: "mares-los-espiritus", label: "Mares - Los Espiritus" },
  { value: "680680-winona-riders", label: "680/680 - Winona Riders" },
  { value: "torteval-gustavo-cerati", label: "Torteval - Gustavo Cerati" },
  { value: "egocripta-babasonicos", label: "Egocripta - Babasonicos" },
  { value: "bajaremos---remastered-don-cornelio-y-la-zona", label: "Bajaremos - Remastered - Don Cornelio Y La Zona" },
  { value: "lite-willy-crook", label: "Lite - Willy Crook" },
  { value: "ameba---remasterizado-2007-soda-stereo", label: "Ameba - Remasterizado 2007 - Soda Stereo" },
  { value: "solid-air-luca-prodan", label: "Solid Air - Luca Prodan" },
  { value: "plateado-sobre-plateado-huellas-en-el-mar-charly-garca", label: "Plateado Sobre Plateado (Huellas En El Mar) - Charly García" },
  { value: "toco-y-me-voy-bersuit-vergarabat", label: "Toco Y Me Voy - Bersuit Vergarabat" },
  { value: "vuelos-bersuit-vergarabat", label: "Vuelos - Bersuit Vergarabat" },
  { value: "legalcenla-viejas-locas", label: "Legalícenla - Viejas Locas" },
  { value: "esa-estrella-era-mi-lujo-patricio-rey-y-sus-redonditos-de-ricota", label: "Esa Estrella Era Mi Lujo - Patricio Rey y sus Redonditos de Ricota" },
  { value: "una-piba-con-la-remera-de-greenpeace-patricio-rey-y-sus-redonditos-de-ricota", label: "Una Piba Con la Remera de Greenpeace - Patricio Rey y sus Redonditos de Ricota" },
  { value: "la-hija-del-fletero-patricio-rey-y-sus-redonditos-de-ricota", label: "La Hija del Fletero - Patricio Rey y sus Redonditos de Ricota" },
  { value: "luzbelito-y-las-sirenas-patricio-rey-y-sus-redonditos-de-ricota", label: "Luzbelito y las Sirenas - Patricio Rey y sus Redonditos de Ricota" },
  { value: "amapola-del-66-divididos", label: "Amapola del 66 - Divididos" },
  { value: "qu-ves-divididos", label: "¿Qué Ves? - Divididos" },
  { value: "zafar-la-vela-puerca", label: "Zafar - La Vela Puerca" },
  { value: "el-farolito-los-piojos", label: "El Farolito - Los Piojos" },
  { value: "civilizacin-los-piojos", label: "Civilización - Los Piojos" },
  { value: "lamento-boliviano-los-enanitos-verdes", label: "Lamento Boliviano - Los Enanitos Verdes" },
  { value: "ella-vendr---remastered-don-cornelio-y-la-zona", label: "Ella Vendrá - Remastered - Don Cornelio Y La Zona" },
  { value: "cenizas-y-diamantes---remastered-don-cornelio-y-la-zona", label: "Cenizas y Diamantes - Remastered - Don Cornelio Y La Zona" },
  { value: "popotitos---live-ser-girn", label: "Popotitos - Live - Serú Girán" },
  { value: "murguita-del-sur-bersuit-vergarabat", label: "Murguita Del Sur - Bersuit Vergarabat" },
  { value: "desconexin-sideral-bersuit-vergarabat", label: "Desconexión Sideral - Bersuit Vergarabat" },
  { value: "la-parte-de-adelante-andrs-calamaro", label: "La parte de adelante - Andrés Calamaro" },
  { value: "loco-andrs-calamaro", label: "Loco - Andrés Calamaro" },
  { value: "una-vela-intoxicados", label: "Una Vela - Intoxicados" },
  { value: "don-electrn-intoxicados", label: "Don Electrón - Intoxicados" },
  { value: "el-tesoro-de-los-inocentes-indio-solari", label: "El Tesoro de los Inocentes - Indio Solari" },
  { value: "no-tengo-ganas-intoxicados", label: "No Tengo Ganas - Intoxicados" },
  { value: "fue-amor-fito-paez", label: "Fue amor - Fito Paez" },
  { value: "cable-a-tierra-fito-paez", label: "Cable A Tierra - Fito Paez" },
  { value: "confesiones-de-invierno-sui-generis", label: "Confesiones de Invierno - Sui Generis" },
  { value: "amor-descartable-virus", label: "Amor Descartable - Virus" },
  { value: "imgenes-paganas-virus", label: "Imágenes Paganas - Virus" },
  { value: "pronta-entrega-virus", label: "Pronta Entrega - Virus" },
  { value: "mirada-speed-virus", label: "Mirada Speed - Virus" },
  { value: "wadu-wadu-virus", label: "Wadu Wadu - Virus" },
  { value: "la-ruta-del-tentempi-charly-garca", label: "La Ruta del Tentempié - Charly García" },
  { value: "last-christmas-wham", label: "Last Christmas - Wham!" },
  { value: "prohibido-callejeros", label: "Prohibido - Callejeros" },
  { value: "amor-amarillo-gustavo-cerati", label: "Amor Amarillo - Gustavo Cerati" },
  { value: "te-llevo-para-que-me-lleves-gustavo-cerati", label: "Te Llevo para Que Me Lleves - Gustavo Cerati" },
  { value: "pulsar-gustavo-cerati", label: "Pulsar - Gustavo Cerati" },
  { value: "tabu-gustavo-cerati", label: "Tabu - Gustavo Cerati" },
  { value: "puente-gustavo-cerati", label: "Puente - Gustavo Cerati" },
  { value: "beautiful-gustavo-cerati", label: "Beautiful - Gustavo Cerati" },
  { value: "cactus-gustavo-cerati", label: "Cactus - Gustavo Cerati" },
  { value: "qu-vas-a-hacer-tan-sola-hoy-viejas-locas", label: "¿Qué Vas A Hacer Tan Sola Hoy? - Viejas Locas" },
  { value: "salir-de-la-melancola-ser-girn", label: "Salir De La Melancolía - Serú Girán" },
  { value: "en-la-ciudad-de-la-furia---mtv-unplugged-soda-stereo", label: "En la Ciudad de la Furia - MTV Unplugged - Soda Stereo" },
  { value: "ella-uso-mi-cabeza-como-un-revolver---mtv-unplugged-soda-stereo", label: "Ella Uso Mi Cabeza Como Un Revolver - MTV Unplugged - Soda Stereo" },
  { value: "un-misil-en-mi-placard---mtv-unplugged-soda-stereo", label: "Un Misil En Mi Placard - MTV Unplugged - Soda Stereo" },
  { value: "entre-canibales---mtv-unplugged-soda-stereo", label: "Entre Canibales - MTV Unplugged - Soda Stereo" },
  { value: "la-rubia-tarada-sumo", label: "La Rubia Tarada - Sumo" },
  { value: "ciudad-de-la-paz-dillom", label: "Ciudad de la Paz - Dillom" },
  { value: "vienen-bajando-el-mat-a-un-polica-motorizado", label: "Vienen Bajando - El Mató a un Policía Motorizado" },
  { value: "chica-rutera-el-mat-a-un-polica-motorizado", label: "Chica Rutera - El Mató a un Policía Motorizado" },
  { value: "camalen---remasterizado-2007-soda-stereo", label: "Camaleón - Remasterizado 2007 - Soda Stereo" },
  { value: "ojos-de-cielo-mercedes-sosa", label: "Ojos de Cielo - Mercedes Sosa" },
  { value: "zona-de-promesas-with-gustavo-cerati-mercedes-sosa", label: "Zona de Promesas (with Gustavo Cerati) - Mercedes Sosa" },
  { value: "la-maza-with-shakira-mercedes-sosa", label: "La Maza (with Shakira) - Mercedes Sosa" },
  { value: "tatuaje-los-subttulos", label: "Tatuaje - los subtítulos" },
  { value: "alma-corazon-y-vida-soledad", label: "Alma, Corazon Y Vida - Soledad" },
  { value: "luna-tucumana-mercedes-sosa", label: "Luna Tucumana - Mercedes Sosa" },
  { value: "la-edad-del-cielo-jorge-drexler", label: "La edad del cielo - Jorge Drexler" },
  { value: "luna-negra-jorge-drexler", label: "Luna negra - Jorge Drexler" },
  { value: "horas-jorge-drexler", label: "Horas - Jorge Drexler" },
  { value: "frontera-jorge-drexler", label: "Frontera - Jorge Drexler" },
  { value: "de-amor-y-de-casualidad-jorge-drexler", label: "De amor y de casualidad - Jorge Drexler" },
  { value: "sea-jorge-drexler", label: "Sea - Jorge Drexler" },
  { value: "un-lugar-en-tu-almohada-jorge-drexler", label: "Un lugar en tu almohada - Jorge Drexler" },
  { value: "me-haces-bien-jorge-drexler", label: "Me haces bien - Jorge Drexler" },
  { value: "antes-jorge-drexler", label: "Antes - Jorge Drexler" },
  { value: "ro-abajo-jorge-drexler", label: "Río abajo - Jorge Drexler" },
  { value: "raquel-jorge-drexler", label: "Raquel - Jorge Drexler" },
  { value: "causa-y-efecto-jorge-drexler", label: "Causa y efecto - Jorge Drexler" },
  { value: "milonga-paraguaya-jorge-drexler", label: "Milonga paraguaya - Jorge Drexler" },
  { value: "princesa-bacana-jorge-drexler", label: "Princesa bacana - Jorge Drexler" },
  { value: "zamba-del-olvido-jorge-drexler", label: "Zamba del olvido - Jorge Drexler" },
  { value: "un-barco-de-sueos-jorge-drexler", label: "Un Barco de Sueños - Jorge Drexler" },
  { value: "la-trama-y-el-desenlace-jorge-drexler", label: "La trama y el desenlace - Jorge Drexler" },
  { value: "toma-el-tren-hacia-el-sur-almendra", label: "Toma el Tren Hacia el Sur - Almendra" },
  { value: "la-luna-de-neuqun-la-vela-puerca", label: "La Luna de Neuquén - La Vela Puerca" },
  { value: "vine-hasta-aqu-los-piojos", label: "Vine Hasta Aquí - Los Piojos" },
  { value: "verano-del-92-los-piojos", label: "Verano del 92 - Los Piojos" },
  { value: "agua-los-piojos", label: "Agua - Los Piojos" },
  { value: "puesto-babasonicos", label: "Puesto - Babasonicos" },
  { value: "carismtico-babasonicos", label: "Carismático - Babasonicos" },
  { value: "microdancing-babasonicos", label: "Microdancing - Babasonicos" },
  { value: "delctrico-babasonicos", label: "Deléctrico - Babasonicos" },
  { value: "los-viejos-vinagres-sumo", label: "Los Viejos Vinagres - Sumo" },
  { value: "estallando-desde-el-ocano-sumo", label: "Estallando Desde el Océano - Sumo" },
  { value: "sandwiches-de-miga-pappos-blues", label: "Sandwiches de Miga - Pappo's Blues" },
  { value: "stratocaster-boogie-pappos-blues", label: "Stratocaster Boogie - Pappo's Blues" },
  { value: "juira-ciro-y-los-persas", label: "Juira! - Ciro y los Persas" },
  { value: "ruleta-los-piojos", label: "Ruleta - Los Piojos" },
  { value: "perrovaca-gertrudis-y-perrovaca", label: "Perrovaca - Gertrudis y Perrovaca" },
  { value: "el-charro-chino-indio-solari", label: "El Charro Chino - Indio Solari" },
  { value: "sucio-y-desprolijo-pappos-blues", label: "Sucio y Desprolijo - Pappo's Blues" },
  { value: "a-1200-km-las-ligas-menores", label: "A 1200 Km - Las Ligas Menores" },
  { value: "afuera-pyramides", label: "Afuera - Pyramides" },
  { value: "los-bajos-fondos-no-somos-marineros", label: "Los Bajos Fondos - No Somos Marineros" },
  { value: "ser-las-pelotas", label: "Será - Las Pelotas" },
  { value: "prejuicios-rbol", label: "Prejuicios - Árbol" },
  { value: "the-last-of-us-gustavo-santaolalla", label: "The Last of Us - Gustavo Santaolalla" },
  { value: "the-last-of-us-part-ii-gustavo-santaolalla", label: "The Last of Us Part II - Gustavo Santaolalla" },
  { value: "himno-de-mi-corazn-with-len-gieco-mercedes-sosa", label: "Himno de Mi Corazón (with León Gieco) - Mercedes Sosa" },
  { value: "zamba-para-olvidarte-with-diego-torres-mercedes-sosa", label: "Zamba para Olvidarte (with Diego Torres) - Mercedes Sosa" },
  { value: "cuando-pase-el-temblor---remasterizado-2007-soda-stereo", label: "Cuando Pase El Temblor - Remasterizado 2007 - Soda Stereo" },
  { value: "ojal-silvio-rodrguez", label: "Ojalá - Silvio Rodríguez" },
  { value: "durazno-y-convencin---jaime-roos-jaime-roos", label: "Durazno y Convención - Jaime Roos - Jaime Roos" },
  { value: "sulky-gustavo-cerati", label: "Sulky - Gustavo Cerati" },
  { value: "hasta-la-raz-natalia-lafourcade", label: "Hasta la Raíz - Natalia Lafourcade" },
  { value: "carnavalito-quebradeo-gauchos-of-the-pampa", label: "Carnavalito Quebradeño - Gauchos Of The Pampa" },
  { value: "el-gigante-juana-aguirre", label: "El Gigante - Juana Aguirre" },
  { value: "huayno-14-bersuit-vergarabat", label: "Huayno 14 - Bersuit Vergarabat" },
  { value: "barro-tal-vez-with-luis-alberto-spinetta-mercedes-sosa", label: "Barro Tal Vez (with Luis Alberto Spinetta) - Mercedes Sosa" },
  { value: "juana-azurduy-mercedes-sosa", label: "Juana Azurduy - Mercedes Sosa" },
  { value: "titan-the-physics-house-band", label: "Titan - The Physics House Band" },
  { value: "vivo-gustavo-cerati", label: "Vivo - Gustavo Cerati" },
  { value: "personalmente-las-pelotas", label: "Personalmente - Las Pelotas" },
  { value: "pandora-todo-aparenta-normal", label: "Pandora - Todo Aparenta Normal" },
  { value: "fsil-mi-amigo-invencible", label: "Fósil - Mi Amigo Invencible" },
  { value: "el-no-lugar-barco", label: "El No Lugar - Barco" },
  { value: "cuatro-vientos-bersuit-vergarabat", label: "Cuatro Vientos - Bersuit Vergarabat" },
  { value: "superlgico-patricio-rey-y-sus-redonditos-de-ricota", label: "Superlógico - Patricio Rey y sus Redonditos de Ricota" },
  { value: "sol-de-abril-todo-aparenta-normal", label: "Sol de Abril - Todo Aparenta Normal" },
  { value: "a-estos-hombres-tristes-almendra", label: "A Estos Hombres Tristes - Almendra" },
  { value: "como-el-viento-voy-a-ver-pescado-rabioso", label: "Como el Viento Voy a Ver - Pescado Rabioso" },
  { value: "diamante-roto-el-mat-a-un-polica-motorizado", label: "Diamante Roto - El Mató a un Policía Motorizado" },
  { value: "todas-las-flores-de-enero-indios", label: "Todas las Flores de Enero - Indios" },
  { value: "pensando-en-m-ill-quentin", label: "pensando en mí - ill quentin" },
  { value: "control-de-daos-ill-quentin", label: "control de daños - ill quentin" },
  { value: "perdn-broke-carrey", label: "PERDÓN - Broke Carrey" },
  { value: "sin-titulos-feat-ill-quentin-juan-lopez", label: "SIN TITULOS (feat. Ill Quentin) - Juan Lopez" },
  { value: "un-tiro-odd-mami", label: "un tiro - ODD MAMI" },
  { value: "inocencia-interrumpida-odd-mami", label: "inocencia interrumpida - ODD MAMI" },
  { value: "azul-ill-quentin", label: "Azul - ill quentin" },
  { value: "eres-para-m-julieta-venegas", label: "Eres para Mí - Julieta Venegas" },
  { value: "a-salvo-nafta", label: "A Salvo - NAFTA" },
  { value: "vmonos-de-viaje-bandalos-chinos", label: "Vámonos De Viaje - Bandalos Chinos" },
  { value: "sper-v-bandalos-chinos", label: "Súper V - Bandalos Chinos" },
  { value: "el-temblor-bandalos-chinos", label: "El Temblor - Bandalos Chinos" },
  { value: "demasiado-bandalos-chinos", label: "Demasiado - Bandalos Chinos" },
  { value: "el-club-de-la-montaa-bandalos-chinos", label: "El Club De La Montaña - Bandalos Chinos" },
  { value: "hermanos-bandalos-chinos", label: "Hermanos - Bandalos Chinos" },
  { value: "tema-de-susana-bandalos-chinos", label: "Tema De Susana - Bandalos Chinos" },
  { value: "lento-bandalos-chinos", label: "Lento - Bandalos Chinos" },
  { value: "tu-rbita-bandalos-chinos", label: "Tu Órbita - Bandalos Chinos" },
  { value: "el-concierto-bandalos-chinos", label: "El Concierto - Bandalos Chinos" },
  { value: "cido-bandalos-chinos", label: "Ácido - Bandalos Chinos" },
  { value: "t-para-tres-en-vivo-estadio-vlez-sarsfield-feat-gustavo-cerati-luis-alberto-spinetta", label: "Té para Tres (En Vivo Estadio Vélez Sarsfield) (feat. Gustavo Cerati) - Luis Alberto Spinetta" },
  { value: "mis-colegas-ska-p", label: "Mis Colegas - Ska-P" },
  { value: "romero-el-madero-ska-p", label: "Romero el Madero - Ska-P" },
  { value: "pa-bailar-siempre-quiero-mas-bajofondo", label: "Pa' Bailar (Siempre Quiero Mas) - Bajofondo" },
  { value: "el-anden-bajofondo", label: "El Anden - Bajofondo" },
  { value: "el-mareo-bajofondo", label: "El Mareo - Bajofondo" },
  { value: "agua-marfil-usted-sealemelo", label: "Agua Marfil - Usted Señalemelo" },
  { value: "consumo-gusto-ska-p", label: "Consumo Gusto - Ska-P" },
  { value: "eres-un-mas-ska-p", label: "Eres Un@ Mas - Ska-P" },
  { value: "tio-sam-ska-p", label: "Tio Sam - Ska-P" },
  { value: "el-vals-del-obrero-ska-p", label: "El Vals del Obrero - Ska-P" },
  { value: "figurate-tu-rodrigo", label: "Figurate Tu - Rodrigo" },
  { value: "lo-mejor-del-amor-rodrigo", label: "Lo mejor del amor - Rodrigo" },
  { value: "ocho-cuarenta-rodrigo", label: "Ocho Cuarenta - Rodrigo" },
  { value: "que-ironia-rodrigo", label: "Que Ironia - Rodrigo" },
  { value: "juana-azurduy-mercedes-sosa", label: "Juana Azurduy - Mercedes Sosa" },
  { value: "barriletes-bersuit-vergarabat", label: "Barriletes - Bersuit Vergarabat" },
  { value: "pandora-todo-aparenta-normal", label: "Pandora - Todo Aparenta Normal" },
  { value: "frou-frou-foxes-in-midsummer-fires-cocteau-twins", label: "Frou-frou Foxes in Midsummer Fires - Cocteau Twins" },
  { value: "todas-las-flores-de-enero-indios", label: "Todas las Flores de Enero - Indios" },
  { value: "triste-cancin-de-amor-la-renga", label: "Triste Canción De Amor - La Renga" },
  { value: "barriletes-bersuit-vergarabat", label: "Barriletes - Bersuit Vergarabat" },
  { value: "toco-y-me-voy-bersuit-vergarabat", label: "Toco Y Me Voy - Bersuit Vergarabat" },
  { value: "un-pacto---live-in-buenos-aires-2001-bersuit-vergarabat", label: "Un Pacto - Live In Buenos Aires / 2001 - Bersuit Vergarabat" },
  { value: "vuelos-bersuit-vergarabat", label: "Vuelos - Bersuit Vergarabat" },
  { value: "qu-vas-a-hacer-tan-sola-hoy-viejas-locas", label: "¿Qué Vas A Hacer Tan Sola Hoy? - Viejas Locas" },
  { value: "lo-artesanal-viejas-locas", label: "Lo Artesanal - Viejas Locas" },
  { value: "el-arbol-de-la-vida-voy-a-dejarte-viejas-locas", label: "El Arbol De La Vida / Voy A Dejarte - Viejas Locas" },
  { value: "qu-vas-a-hacer-tan-sola-hoy---spotify-singles-dillom", label: "¿Qué Vas A Hacer Tan Sola Hoy? - Spotify Singles - Dillom" },
  { value: "las-cosas-que-no-se-tocan-intoxicados", label: "Las cosas que no se tocan - Intoxicados" },
  { value: "homero-viejas-locas", label: "Homero - Viejas Locas" },
  { value: "creo-callejeros", label: "Creo - Callejeros" },
  { value: "volver-a-casa-intoxicados", label: "Volver a Casa - Intoxicados" },
  { value: "legalcenla-viejas-locas", label: "Legalícenla - Viejas Locas" },
  { value: "balada-para-otra-mujer-viejas-locas", label: "Balada Para Otra Mujer - Viejas Locas" },
  { value: "omega-feat-ralphie-choo-rosala", label: "Omega (feat. Ralphie Choo) - ROSALÍA" },
  { value: "malamente---cap1-augurio-rosala", label: "MALAMENTE - Cap.1: Augurio - ROSALÍA" },
  { value: "new-woman-feat-rosala-lisa", label: "New Woman (feat. ROSALÍA) - LISA" },
  { value: "bagdad---cap7-liturgia-rosala", label: "BAGDAD - Cap.7: Liturgia - ROSALÍA" },
  { value: "tkn-feat-travis-scott-rosala", label: "TKN (feat. Travis Scott) - ROSALÍA" },
  { value: "a-ningn-hombre---cap11-poder-rosala", label: "A NINGÚN HOMBRE - Cap.11: Poder - ROSALÍA" },
  { value: "como-un-g-rosala", label: "COMO UN G - ROSALÍA" },
  { value: "pienso-en-tu-mir---cap3-celos-rosala", label: "PIENSO EN TU MIRÁ - Cap.3: Celos - ROSALÍA" },
  { value: "aute-cuture-rosala", label: "Aute Cuture - ROSALÍA" },
  { value: "bizcochito-rosala", label: "BIZCOCHITO - ROSALÍA" },
  { value: "saoko-rosala", label: "SAOKO - ROSALÍA" },
  { value: "linda-tokischa", label: "Linda - Tokischa" },
  { value: "catalina-rosala", label: "Catalina - ROSALÍA" },
  { value: "klk-arca", label: "KLK - Arca" },
  { value: "di-mi-nombre---cap8-xtasis-rosala", label: "DI MI NOMBRE - Cap.8: Éxtasis - ROSALÍA" },
  { value: "la-combi-versace-rosala", label: "LA COMBI VERSACE - ROSALÍA" },
  { value: "chicken-teriyaki-rosala", label: "CHICKEN TERIYAKI - ROSALÍA" },
  { value: "buleras-rosala", label: "BULERÍAS - ROSALÍA" },
  { value: "motomami-rosala", label: "MOTOMAMI - ROSALÍA" },
  { value: "playground-love-air", label: "Playground Love - Air" },
  { value: "this-old-dog-mac-demarco", label: "This Old Dog - Mac DeMarco" },
  { value: "like-a-tattoo-sade", label: "Like a Tattoo - Sade" },
  { value: "eyes-without-a-face-billy-idol", label: "Eyes Without A Face - Billy Idol" },
  { value: "cherry-blossom-girl-air", label: "Cherry Blossom Girl - Air" },
  { value: "only-you-portishead", label: "Only You - Portishead" },
  { value: "bending-hectic-the-smile", label: "Bending Hectic - The Smile" },
  { value: "master-of-none-beach-house", label: "Master of None - Beach House" },
  { value: "cherry-coloured-funk-cocteau-twins", label: "Cherry-coloured Funk - Cocteau Twins" },
  { value: "venus-air", label: "Venus - Air" },
  { value: "ghostride-crumb", label: "Ghostride - Crumb" },
  { value: "girl-boy-blonde-redhead", label: "Girl Boy - Blonde Redhead" },
  { value: "the-rip-portishead", label: "The Rip - Portishead" },
  { value: "will-i-see-you-again-thee-sacred-souls", label: "Will I See You Again? - Thee Sacred Souls" },
  { value: "breathe-in-the-air-pink-floyd", label: "Breathe (In the Air) - Pink Floyd" },
  { value: "desafinado-stan-getz", label: "Desafinado - Stan Getz" },
  { value: "how-does-it-make-you-feel-air", label: "How Does It Make You Feel? - Air" },
  { value: "20191009-i-like-her-mac-demarco", label: "20191009 I Like Her - Mac DeMarco" },
  { value: "dreams---2004-remaster-fleetwood-mac", label: "Dreams - 2004 Remaster - Fleetwood Mac" },
  { value: "roads-portishead", label: "Roads - Portishead" },
  { value: "diamanteskalashnikov-saramalacara", label: "DIAMANTES&KALASHNIKOV - Saramalacara" },
  { value: "tu-droga-saramalacara", label: "tu droga - Saramalacara" },
  { value: "seales-de-humo-broke-carrey", label: "Señales de Humo - Broke Carrey" },
  { value: "ovario-dillom", label: "OVARIO - Dillom" },
  { value: "minimi-dillom", label: "MINIMI - Dillom" },
  { value: "control-de-daos-ill-quentin", label: "control de daños - ill quentin" },
  { value: "montonero-broke-carrey", label: "Montonero - Broke Carrey" },
  { value: "distinto-broke-carrey", label: "Distinto - Broke Carrey" },
  { value: "nmeros-rojos-ill-quentin", label: "números rojos - ill quentin" },
  { value: "1312-portarme-mal-odd-mami", label: "1312 (Portarme Mal) - ODD MAMI" },
  { value: "humo-saramalacara", label: "HUMO - Saramalacara" },
  { value: "danza-de-la-lluvia-ill-quentin", label: "danza de la lluvia - ill quentin" },
  { value: "pensando-en-m-ill-quentin", label: "pensando en mí - ill quentin" },
  { value: "me-gusta-que-me-odies-ill-quentin", label: "Me Gusta Que Me Odies - ill quentin" },
  { value: "ultra-odd-mami", label: "Ultra - ODD MAMI" },
  { value: "perdn-broke-carrey", label: "PERDÓN - Broke Carrey" },
  { value: "me-odio-broke-carrey", label: "ME ODIO - Broke Carrey" },
  { value: "un-tiro-odd-mami", label: "un tiro - ODD MAMI" },
  { value: "inocencia-interrumpida-odd-mami", label: "inocencia interrumpida - ODD MAMI" },
  { value: "azul-ill-quentin", label: "Azul - ill quentin" },
  { value: "sin-titulos-feat-ill-quentin-juan-lopez", label: "SIN TITULOS (feat. Ill Quentin) - Juan Lopez" },
  { value: "intentarlo-odd-mami", label: "intentarlo - ODD MAMI" },
  { value: "gwen-everest-panchiko", label: "Gwen Everest - Panchiko" },
  { value: "in-between-title-fight", label: "In-Between - Title Fight" },
  { value: "permanent-daylight-radiohead", label: "Permanent Daylight - Radiohead" },
  { value: "until-i-know-panchiko", label: "Until I Know - Panchiko" },
  { value: "robotsreprise-panchiko", label: "R>O>B>O>T>S>R>E>P>R>I>S>E - Panchiko" },
  { value: "black-star-radiohead", label: "Black Star - Radiohead" },
  { value: "1979---remastered-2012-the-smashing-pumpkins", label: "1979 - Remastered 2012 - The Smashing Pumpkins" },
  { value: "alison-slowdive", label: "Alison - Slowdive" },
  { value: "wildflower-beach-house", label: "Wildflower - Beach House" },
  { value: "when-the-sun-hits-slowdive", label: "When the Sun Hits - Slowdive" },
  { value: "my-favourite-game-the-cardigans", label: "My Favourite Game - The Cardigans" },
  { value: "untitled-acoustic-song---live-panchiko", label: "Untitled Acoustic Song - Live - Panchiko" },
  { value: "think-thats-too-wise-panchiko", label: "Think That's Too Wise - Panchiko" },
  { value: "", label: "まほうのじゅうたん - 百景" },
  { value: "once-then-well-be-free-wisp", label: "Once then we'll be free - Wisp" },
  { value: "knives-out-radiohead", label: "Knives Out - Radiohead" },
  { value: "playas-oscuras-los-visitantes", label: "Playas Oscuras - Los Visitantes" },
  { value: "noche-azul-los-visitantes", label: "Noche Azul - Los Visitantes" },
  { value: "pi-pa-pu-los-visitantes", label: "Pi-Pa-Pu - Los Visitantes" },
  { value: "estar-los-visitantes", label: "Estaré - Los Visitantes" },
  { value: "bi-bap-um-dera-los-visitantes", label: "Bi Bap Um Dera - Los Visitantes" },
  { value: "cenizas-y-diamantes---remastered-don-cornelio-y-la-zona", label: "Cenizas y Diamantes - Remastered - Don Cornelio Y La Zona" },
  { value: "tazas-de-t-chino---remastered-don-cornelio-y-la-zona", label: "Tazas De Té Chino - Remastered - Don Cornelio Y La Zona" },
  { value: "ella-vendra-palo-pandolfo", label: "Ella Vendra - Palo Pandolfo" },
  { value: "el-alma-partida-palo-pandolfo", label: "El Alma Partida - Palo Pandolfo" },
  { value: "a-travs-de-los-sueos-palo-pandolfo", label: "A Través De Los Sueños - Palo Pandolfo" },
  { value: "karma-policia-palo-pandolfo", label: "Karma Policia - Palo Pandolfo" },
  { value: "ceniza-a-cenizas-palo-pandolfo", label: "Ceniza a Cenizas - Palo Pandolfo" },
  { value: "tu-amor-palo-pandolfo", label: "Tu Amor - Palo Pandolfo" },
  { value: "madrigal-palo-pandolfo", label: "Madrigal - Palo Pandolfo" },
  { value: "antojo-palo-pandolfo", label: "Antojo - Palo Pandolfo" },
  { value: "prpados-palo-pandolfo", label: "Párpados - Palo Pandolfo" },
  { value: "hipercandombe-palo-pandolfo", label: "Hipercandombe - Palo Pandolfo" },
  { value: "el-rosario-en-el-muro---remastered-don-cornelio-y-la-zona", label: "El Rosario En El Muro - Remastered - Don Cornelio Y La Zona" },
  { value: "imagen-proyectada---remastered-don-cornelio-y-la-zona", label: "Imagen Proyectada - Remastered - Don Cornelio Y La Zona" },
  { value: "ella-palo-pandolfo", label: "Ella - Palo Pandolfo" },
  { value: "esa-estrella-era-mi-lujo-patricio-rey-y-sus-redonditos-de-ricota", label: "Esa Estrella Era Mi Lujo - Patricio Rey y sus Redonditos de Ricota" },
  { value: "vencedores-vencidos-patricio-rey-y-sus-redonditos-de-ricota", label: "Vencedores Vencidos - Patricio Rey y sus Redonditos de Ricota" },
  { value: "angel-de-los-perdedores-el-soldado", label: "Angel de los Perdedores - El Soldado" },
  { value: "una-piba-con-la-remera-de-greenpeace-patricio-rey-y-sus-redonditos-de-ricota", label: "Una Piba Con la Remera de Greenpeace - Patricio Rey y sus Redonditos de Ricota" },
  { value: "la-hija-del-fletero-patricio-rey-y-sus-redonditos-de-ricota", label: "La Hija del Fletero - Patricio Rey y sus Redonditos de Ricota" },
  { value: "semen-up-patricio-rey-y-sus-redonditos-de-ricota", label: "Semen-Up - Patricio Rey y sus Redonditos de Ricota" },
  { value: "el-templo-de-momo-patricio-rey-y-sus-redonditos-de-ricota", label: "El Templo de Momo - Patricio Rey y sus Redonditos de Ricota" },
  { value: "ella-debe-estar-tan-linda-patricio-rey-y-sus-redonditos-de-ricota", label: "Ella Debe Estar Tan Linda - Patricio Rey y sus Redonditos de Ricota" },
  { value: "ropa-sucia-patricio-rey-y-sus-redonditos-de-ricota", label: "Ropa Sucia - Patricio Rey y sus Redonditos de Ricota" },
  { value: "el-pibe-de-los-astilleros-patricio-rey-y-sus-redonditos-de-ricota", label: "El Pibe de los Astilleros - Patricio Rey y sus Redonditos de Ricota" },
  { value: "luzbelito-y-las-sirenas-patricio-rey-y-sus-redonditos-de-ricota", label: "Luzbelito y las Sirenas - Patricio Rey y sus Redonditos de Ricota" },
  { value: "yo-canbal-patricio-rey-y-sus-redonditos-de-ricota", label: "Yo Caníbal - Patricio Rey y sus Redonditos de Ricota" },
  { value: "preso-en-mi-ciudad-patricio-rey-y-sus-redonditos-de-ricota", label: "Preso en Mi Ciudad - Patricio Rey y sus Redonditos de Ricota" },
  { value: "fuegos-de-octubre-patricio-rey-y-sus-redonditos-de-ricota", label: "Fuegos de Octubre - Patricio Rey y sus Redonditos de Ricota" },
  { value: "tren-de-fugitivos-el-soldado", label: "Tren de Fugitivos - El Soldado" },
  { value: "las-increbles-andanzas-del-capitn-buscapina-en-cybersiberia-patricio-rey-y-sus-redonditos-de-ricota", label: "Las Increíbles Andanzas del Capitán Buscapina en Cybersiberia - Patricio Rey y sus Redonditos de Ricota" },
  { value: "el-tesoro-de-los-inocentes-indio-solari", label: "El Tesoro de los Inocentes - Indio Solari" },
  { value: "salando-las-heridas-patricio-rey-y-sus-redonditos-de-ricota", label: "Salando las Heridas - Patricio Rey y sus Redonditos de Ricota" },
  { value: "mariposa-pontiac---rock-del-pas-patricio-rey-y-sus-redonditos-de-ricota", label: "Mariposa Pontiac - Rock del País - Patricio Rey y sus Redonditos de Ricota" },
  { value: "y-mientras-tanto-el-sol-se-muere-indio-solari", label: "Y Mientras Tanto el Sol Se Muere... - Indio Solari" },
  { value: "strangerdanger-indio-solari", label: "Strangerdanger - Indio Solari" },
  { value: "hroe-del-whisky-patricio-rey-y-sus-redonditos-de-ricota", label: "Héroe del Whisky - Patricio Rey y sus Redonditos de Ricota" },
  { value: "fusilados-por-la-cruz-roja-patricio-rey-y-sus-redonditos-de-ricota", label: "Fusilados por la Cruz Roja - Patricio Rey y sus Redonditos de Ricota" },
  { value: "whats-going-on-marvin-gaye", label: "What's Going On - Marvin Gaye" },
  { value: "right-down-the-line-gerry-rafferty", label: "Right Down the Line - Gerry Rafferty" },
  { value: "ex-factor-ms-lauryn-hill", label: "Ex-Factor - Ms. Lauryn Hill" },
  { value: "aint-no-sunshine-bill-withers", label: "Ain't No Sunshine - Bill Withers" },
  { value: "doo-wop-that-thing-ms-lauryn-hill", label: "Doo Wop (That Thing) - Ms. Lauryn Hill" },
  { value: "a-sunday-kind-of-love-etta-james", label: "A Sunday Kind Of Love - Etta James" },
  { value: "distant-lover-marvin-gaye", label: "Distant Lover - Marvin Gaye" },
  { value: "killing-me-softly-with-his-song-fugees", label: "Killing Me Softly With His Song - Fugees" },
  { value: "to-zion-feat-carlos-santana-ms-lauryn-hill", label: "To Zion (feat. Carlos Santana) - Ms. Lauryn Hill" },
  { value: "ready-or-not-ms-lauryn-hill", label: "Ready Or Not - Ms. Lauryn Hill" },
  { value: "is-it-a-crime-sade", label: "Is It a Crime - Sade" },
  { value: "kiss-of-life-sade", label: "Kiss of Life - Sade" },
  { value: "golden-jill-scott", label: "Golden - Jill Scott" },
  { value: "your-love-is-king-sade", label: "Your Love Is King - Sade" },
  { value: "jezebel-sade", label: "Jezebel - Sade" },
  { value: "sally-sade", label: "Sally - Sade" },
  { value: "doo-wop---that-thing-quantic", label: "Doo Wop - That Thing - Quantic" },
  { value: "oyeme-ana-tijoux", label: "Oyeme - Ana Tijoux" },
  { value: "millonaria-ana-tijoux", label: "Millonaria - Ana Tijoux" },
  { value: "a-ningn-hombre---cap11-poder-rosala", label: "A NINGÚN HOMBRE - Cap.11: Poder - ROSALÍA" },
  { value: "malamente---cap1-augurio-rosala", label: "MALAMENTE - Cap.1: Augurio - ROSALÍA" },
  { value: "linda-tokischa", label: "Linda - Tokischa" },
  { value: "aguardiente-sofa-gabanna", label: "Aguardiente - Sofía Gabanna" },
  { value: "flaco-sofa-gabanna", label: "Flaco - Sofía Gabanna" },
  { value: "eres-para-m-julieta-venegas", label: "Eres para Mí - Julieta Venegas" },
  { value: "cora-ana-tijoux", label: "Cora - Ana Tijoux" },
  { value: "mi-verdad-ana-tijoux", label: "Mi Verdad - Ana Tijoux" },
  { value: "la-fama-rosala", label: "LA FAMA - ROSALÍA" },
  { value: "kamikaze-sofa-gabanna", label: "Kamikaze - Sofía Gabanna" },
  { value: "sideral-sofa-gabanna", label: "Sideral - Sofía Gabanna" },
  { value: "dime-que-ana-tijoux", label: "Dime que - Ana Tijoux" },
  { value: "cada-loco-con-su-tema-sofa-gabanna", label: "Cada Loco Con Su Tema - Sofía Gabanna" },
  { value: "tu-sae-ana-tijoux", label: "Tu sae - Ana Tijoux" },
  { value: "la-combi-versace-rosala", label: "LA COMBI VERSACE - ROSALÍA" },
  { value: "reversible-sofa-gabanna", label: "Reversible - Sofía Gabanna" },
  { value: "candy-rosala", label: "CANDY - ROSALÍA" },
  { value: "bizcochito-rosala", label: "BIZCOCHITO - ROSALÍA" },
  { value: "diablo-rosala", label: "DIABLO - ROSALÍA" },
  { value: "a-veces-ana-tijoux", label: "A Veces - Ana Tijoux" },
  { value: "nada-es-para-siempre-dj-tee", label: "Nada es para siempre - DJ TEE" },
  { value: "ya-no-tengo-pena-neim", label: "Ya no tengo pena - Neim" },
  { value: "contando-ovejas-wos", label: "CONTANDO OVEJAS - WOS" },
  { value: "alma-dinamita-wos", label: "ALMA DINAMITA - WOS" },
  { value: "quereme-louta", label: "QUEREME - LOUTA" },
  { value: "lleno-de-zafiros-wos", label: "LLENO DE ZAFIROS - WOS" },
  { value: "algo-del-vaco-wos", label: "ALGO DEL VACÍO - WOS" },
  { value: "ojeras-negras-wos", label: "OJERAS NEGRAS - WOS" },
  { value: "andrmeda-wos", label: "ANDRÓMEDA - WOS" },
  { value: "mir-mam-wos", label: "MIRÁ MAMÁ - WOS" },
  { value: "mugre-wos", label: "MUGRE - WOS" },
  { value: "meln-vino-wos", label: "MELÓN VINO - WOS" },
  { value: "terraza-wos", label: "TERRAZA - WOS" },
  { value: "okupa-wos", label: "OKUPA - WOS" },
  { value: "fresco-wos", label: "FRESCO - WOS" },
  { value: "morfeo-wos", label: "MORFEO - WOS" },
  { value: "pared-de-cristal-wos", label: "PARED DE CRISTAL - WOS" },
  { value: "220-dillom", label: "220 - Dillom" },
  { value: "amigos-nuevos-dillom", label: "AMIGOS NUEVOS - Dillom" },
  { value: "bicicleta-dillom", label: "BICICLETA - Dillom" },
  { value: "la-primera-dillom", label: "LA PRIMERA - Dillom" },
  { value: "bien-o-mal-trueno", label: "BIEN O MAL - Trueno" },
  { value: "rain-trueno", label: "Rain - Trueno" },
  { value: "feel-me-trueno", label: "FEEL ME?? - Trueno" },
  { value: "solo-por-vos-trueno", label: "SOLO POR VOS - Trueno" },
  { value: "nuevas-coordenadas-wos", label: "NUEVAS COORDENADAS - WOS" },
  { value: "que-se-haga-tarde-wos", label: "QUE SE HAGA TARDE - WOS" },
  { value: "la-niebla-wos", label: "LA NIEBLA - WOS" },
  { value: "sauce-dillom", label: "Sauce - Dillom" },
  { value: "culpa-wos", label: "CULPA - WOS" },
  { value: "eclipse-zeballos", label: "Eclipse - Zeballos" },
  { value: "rocketpowers-dillom", label: "ROCKETPOWERS - Dillom" },
  { value: "ciudad-de-la-paz-dillom", label: "Ciudad de la Paz - Dillom" },
  { value: "protocolo-banzai-fc", label: "Protocolo - Banzai FC" },
  { value: "cmere---skit-bilal", label: "C'mere - Skit - Bilal" },
  { value: "when-will-u-call-bilal", label: "When Will U Call - Bilal" },
  { value: "on-erykah-badu", label: "...& On - Erykah Badu" },
  { value: "please-dont-make-me-cry-lianne-la-havas", label: "Please Don't Make Me Cry - Lianne La Havas" },
  { value: "igors-theme-tyler-the-creator", label: "IGOR'S THEME - Tyler, The Creator" },
  { value: "cleva-erykah-badu", label: "Cleva - Erykah Badu" },
  { value: "afro-blue-robert-glasper", label: "Afro Blue - Robert Glasper" },
  { value: "didnt-cha-know-erykah-badu", label: "Didn't Cha Know - Erykah Badu" },
  { value: "orange-moon-erykah-badu", label: "Orange Moon - Erykah Badu" },
  { value: "doo-wop-that-thing-ms-lauryn-hill", label: "Doo Wop (That Thing) - Ms. Lauryn Hill" },
  { value: "ex-factor-ms-lauryn-hill", label: "Ex-Factor - Ms. Lauryn Hill" },
  { value: "to-zion-feat-carlos-santana-ms-lauryn-hill", label: "To Zion (feat. Carlos Santana) - Ms. Lauryn Hill" },
  { value: "walk-on-by-thundercat", label: "Walk On By - Thundercat" },
  { value: "show-you-the-way-thundercat", label: "Show You The Way - Thundercat" },
  { value: "its-love-2020-remastered-jill-scott", label: "It's Love (2020 Remastered) - Jill Scott" },
  { value: "the-way-2020-remastered-jill-scott", label: "The Way (2020 Remastered) - Jill Scott" },
  { value: "read-my-mind-lianne-la-havas", label: "Read My Mind - Lianne La Havas" },
  { value: "id-rather-go-blind-etta-james", label: "I'd Rather Go Blind - Etta James" },
  { value: "these-walls-kendrick-lamar", label: "These Walls - Kendrick Lamar" },
  { value: "cancion-para-los-das-de-la-vida-luis-alberto-spinetta", label: "Cancion para los Días de la Vida - Luis Alberto Spinetta" },
  { value: "quedndote-o-yndote-luis-alberto-spinetta", label: "Quedándote o Yéndote - Luis Alberto Spinetta" },
  { value: "almendra-luis-alberto-spinetta", label: "Almendra - Luis Alberto Spinetta" },
  { value: "cancin-para-mi-muerte-sui-generis", label: "Canción para Mi Muerte - Sui Generis" },
  { value: "cenizas-y-diamantes---remastered-don-cornelio-y-la-zona", label: "Cenizas y Diamantes - Remastered - Don Cornelio Y La Zona" },
  { value: "vuelos-bersuit-vergarabat", label: "Vuelos - Bersuit Vergarabat" },
  { value: "confesiones-de-invierno-sui-generis", label: "Confesiones de Invierno - Sui Generis" },
  { value: "t-para-tres-en-vivo-estadio-vlez-sarsfield-feat-gustavo-cerati-luis-alberto-spinetta", label: "Té para Tres (En Vivo Estadio Vélez Sarsfield) (feat. Gustavo Cerati) - Luis Alberto Spinetta" },
  { value: "quizs-porque-sui-generis", label: "Quizás, Porque - Sui Generis" },
  { value: "muchacha-ojos-de-papel-almendra", label: "Muchacha (Ojos de Papel) - Almendra" },
  { value: "ojos-de-video-tape-charly-garca", label: "Ojos De Video Tape - Charly García" },
  { value: "plegaria-para-un-nio-dormido-almendra", label: "Plegaria para un Niño Dormido - Almendra" },
  { value: "el-anillo-del-capitn-beto-invisible", label: "El Anillo del Capitán Beto - Invisible" },
  { value: "los-libros-de-la-buena-memoria-invisible", label: "Los Libros de la Buena Memoria - Invisible" },
  { value: "barro-tal-vez-with-luis-alberto-spinetta-mercedes-sosa", label: "Barro Tal Vez (with Luis Alberto Spinetta) - Mercedes Sosa" },
  { value: "zona-de-promesas-with-gustavo-cerati-mercedes-sosa", label: "Zona de Promesas (with Gustavo Cerati) - Mercedes Sosa" },
  { value: "alfonsina-y-el-mar-mercedes-sosa", label: "Alfonsina Y El Mar - Mercedes Sosa" },
  { value: "viernes-3am---2019-remasterizado-ser-girn", label: "Viernes, 3AM - 2019 Remasterizado - Serú Girán" },
  { value: "adela-en-el-carrousell-charly-garca", label: "Adela en el Carrousell - Charly García" },
  { value: "la-mquina-de-ser-feliz-charly-garca", label: "La Máquina de Ser Feliz - Charly García" },
  { value: "corazn-delator-soda-stereo", label: "Corazón Delator - Soda Stereo" },
  { value: "los-dinosaurios-charly-garca", label: "Los Dinosaurios - Charly García" },
  { value: "el-tuerto-y-los-ciegos-sui-generis", label: "El Tuerto y los Ciegos - Sui Generis" },
  { value: "estacin-sui-generis", label: "Estación - Sui Generis" },
  { value: "cinema-verit-ser-girn", label: "Cinema Verité - Serú Girán" },
  { value: "eiti-leda---2021-remasterizado-ser-girn", label: "Eiti-Leda - 2021 Remasterizado - Serú Girán" },
  { value: "yo-vengo-a-ofrecer-mi-corazon-fito-paez", label: "Yo Vengo A Ofrecer Mi Corazon - Fito Paez" },
  { value: "el-alma-partida-palo-pandolfo", label: "El Alma Partida - Palo Pandolfo" },
  { value: "perdonado-nio-condenado-invisible", label: "Perdonado (Niño Condenado) - Invisible" },
  { value: "ahbasta-de-pensar-luis-alberto-spinetta", label: "¡Ah!...Basta de Pensar - Luis Alberto Spinetta" },
  { value: "cuando-comenzamos-a-nacer-sui-generis", label: "Cuando Comenzamos a Nacer - Sui Generis" },
  { value: "toda-la-vida-tiene-msica-hoy-luis-alberto-spinetta", label: "Toda la Vida Tiene Música Hoy - Luis Alberto Spinetta" },
  { value: "melting-kali-uchis", label: "Melting - Kali Uchis" },
  { value: "i-think-i-left-the-stove-on-hotel-ugly", label: "I Think I Left the Stove On - Hotel Ugly" },
  { value: "borderline-tame-impala", label: "Borderline - Tame Impala" },
  { value: "mirage-orion-sun", label: "Mirage - Orion Sun" },
  { value: "stevie-doesnt-wonder-hotel-ugly", label: "Stevie Doesn't Wonder - Hotel Ugly" },
  { value: "the-ballad-of-eddie-jabuley-hotel-ugly", label: "The Ballad of Eddie Jabuley - Hotel Ugly" },
  { value: "just-a-stranger-feat-steve-lacy-kali-uchis", label: "Just A Stranger (feat. Steve Lacy) - Kali Uchis" },
  { value: "after-the-storm-feat-tyler-the-creator-bootsy-collins-kali-uchis", label: "After The Storm (feat. Tyler, The Creator & Bootsy Collins) - Kali Uchis" },
  { value: "telepata-kali-uchis", label: "telepatía - Kali Uchis" },
  { value: "infrunami-steve-lacy", label: "Infrunami - Steve Lacy" },
  { value: "moonlight-kali-uchis", label: "Moonlight - Kali Uchis" },
  { value: "igual-que-un-ngel-with-peso-pluma-kali-uchis", label: "Igual Que Un Ángel (with Peso Pluma) - Kali Uchis" },
  { value: "see-you-again-feat-kali-uchis-tyler-the-creator", label: "See You Again (feat. Kali Uchis) - Tyler, The Creator" },
  { value: "dead-to-me-kali-uchis", label: "Dead To Me - Kali Uchis" },
  { value: "amiga-da-minha-mulher-seu-jorge", label: "Amiga da Minha Mulher - Seu Jorge" },
  { value: "dois-beijinhos-seu-jorge", label: "Dois Beijinhos - Seu Jorge" },
  { value: "mina-do-condomnio-seu-jorge", label: "Mina do Condomínio - Seu Jorge" },
  { value: "menina-mulher-da-pele-preta-jorge-ben-jor", label: "Menina Mulher Da Pele Preta - Jorge Ben Jor" },
  { value: "carolina-seu-jorge", label: "Carolina - Seu Jorge" },
  { value: "mas-que-nada-jorge-ben-jor", label: "Mas, Que Nada! - Jorge Ben Jor" },
  { value: "proposta-gilsons", label: "Proposta - Gilsons" },
  { value: "mistrio-do-planeta-novos-baianos", label: "Mistério do Planeta - Novos Baianos" },
  { value: "lado-vazio-do-sof-rodrigo-alarcon", label: "Lado Vazio do Sofá - Rodrigo Alarcon" },
  { value: "alvorada-cartola", label: "Alvorada - Cartola" },
  { value: "coisa-mais-linda-rosa-passos", label: "Coisa Mais Linda - Rosa Passos" },
  { value: "samba-de-uma-nota-s-rosa-passos", label: "Samba de uma Nota Só - Rosa Passos" },
  { value: "gua-de-beber-quarteto-jobim-morelenbaum", label: "Água de Beber - Quarteto Jobim-Morelenbaum" },
  { value: "casa-de-noca-maria-rita", label: "Casa de Noca - Maria Rita" },
  { value: "vrias-queixas-gilsons", label: "Várias Queixas - Gilsons" },
  { value: "onde-anda-voc-toquinho", label: "Onde Anda Você - Toquinho" },
  { value: "love-love-gilsons", label: "Love Love - Gilsons" },
  { value: "devagarinho-gilsons", label: "Devagarinho - Gilsons" },
  { value: "eterna-busca-seu-jorge", label: "Eterna Busca - Seu Jorge" },
  { value: "chove-chuva-jorge-ben-jor", label: "Chove Chuva - Jorge Ben Jor" },
  { value: "a-menina-dana-novos-baianos", label: "A Menina Dança - Novos Baianos" },
  { value: "ltimo-romance-los-hermanos", label: "Último Romance - Los Hermanos" },
  { value: "ru-confesso-tim-maia", label: "Réu Confesso - Tim Maia" },
  { value: "culpa-o-terno", label: "Culpa - O Terno" },
  { value: "trem-das-onze-adoniran-barbosa", label: "Trem Das Onze - Adoniran Barbosa" },
  { value: "cu-da-boca-castello-branco", label: "Céu da Boca - Castello Branco" },
  { value: "malemolencia-cu", label: "Malemolencia - Céu" },
  { value: "bateu-gilsons", label: "Bateu - Gilsons" },
  { value: "festa-de-adeus-julio-secchin", label: "FESTA DE ADEUS - Julio Secchin" },
  { value: "figa-de-guin-alcione", label: "Figa De Guiné - Alcione" },
  { value: "crianada-castello-branco", label: "Criançada - Castello Branco" },
  { value: "de-noite-na-cama-bid", label: "De Noite Na Cama - BiD" },
  { value: "everything-i-am-kanye-west", label: "Everything I Am - Kanye West" },
  { value: "let-go-aaron-may", label: "Let Go - Aaron May" },
  { value: "ocean-prime-feat-boldy-james-the-alchemist", label: "Ocean Prime (feat. Boldy James) - The Alchemist" },
  { value: "gorgeous-kanye-west", label: "Gorgeous - Kanye West" },
  { value: "silkk-da-shocka-feat-syd-isaiah-rashad", label: "Silkk da Shocka (feat. Syd) - Isaiah Rashad" },
  { value: "e-coli-feat-earl-sweatshirt-the-alchemist", label: "E. Coli (feat. Earl Sweatshirt) - The Alchemist" },
  { value: "life-mac-miller", label: "Life - Mac Miller" },
  { value: "come-back-to-earth-mac-miller", label: "Come Back to Earth - Mac Miller" },
  { value: "back-in-the-day-mac-miller", label: "Back In The Day - Mac Miller" },
  { value: "spaceship-kanye-west", label: "Spaceship - Kanye West" },
  { value: "flashing-lights-kanye-west", label: "Flashing Lights - Kanye West" },
  { value: "objects-in-the-mirror-mac-miller", label: "Objects in the Mirror - Mac Miller" },
  { value: "pride-kendrick-lamar", label: "PRIDE. - Kendrick Lamar" },
  { value: "i-wonder-kanye-west", label: "I Wonder - Kanye West" },
  { value: "riot-earl-sweatshirt", label: "Riot! - Earl Sweatshirt" },
  { value: "in-love-aaron-may", label: "In Love - Aaron May" },
  { value: "im-good-luv-enjoy-aaron-may", label: "I'm Good Luv, Enjoy. - Aaron May" },
  { value: "burn", label: "BURN - ¥$" },
  { value: "4-your-eyez-only-j-cole", label: "4 Your Eyez Only - J. Cole" },
  { value: "no-role-modelz-j-cole", label: "No Role Modelz - J. Cole" },
  { value: "ride-aaron-may", label: "Ride - Aaron May" },
  { value: "gristle-blvck-svm", label: "gristle - Blvck Svm" },
  { value: "time-aaron-may", label: "Time - Aaron May" },
  { value: "congratulations-feat-bilal-mac-miller", label: "Congratulations (feat. Bilal) - Mac Miller" },
  { value: "xxx-feat-u2-kendrick-lamar", label: "XXX. FEAT. U2. - Kendrick Lamar" },
  { value: "pulso-nenagenix", label: "Pulso - Nenagenix" },
  { value: "chica-gotika-sakatumba", label: "Chica Gotika - Sakatumba" },
  { value: "igual-nenagenix", label: "Igual - Nenagenix" },
  { value: "nadar-sola-nenagenix", label: "Nadar Sola - Nenagenix" },
  { value: "ya-no-odd-mami", label: "Ya No - ODD MAMI" },
  { value: "antro-playa-nudista", label: "Antro - Playa Nudista" },
  { value: "material-pornogrfico-nenagenix", label: "Material Pornográfico - Nenagenix" },
  { value: "asking-4-it-nenagenix", label: "Asking 4 It - Nenagenix" },
  { value: "desmotivada-buenos-vampiros", label: "Desmotivada - Buenos Vampiros" },
  { value: "no-te-perdono-mugre", label: "No Te Perdono - MUGRE" },
  { value: "cuidado-mora-y-los-metegoles", label: "Cuidado - Mora y los Metegoles" },
  { value: "terremoto-dum-chica", label: "Terremoto - Dum Chica" },
  { value: "dientes-de-leche-nenagenix", label: "Dientes de Leche - Nenagenix" },
  { value: "trfico-kill-flora", label: "Tráfico - Kill Flora" },
  { value: "el-hit-dum-chica", label: "El Hit - Dum Chica" },
  { value: "sueo-por-debajo-nenagenix", label: "Sueño por Debajo - Nenagenix" },
  { value: "asfixia-nenagenix", label: "Asfixia - Nenagenix" },
  { value: "separados-al-nacer-winona-riders", label: "Separados Al Nacer - Winona Riders" },
  { value: "carta-a-mi-pap-akriila", label: "carta a mi papá - AKRIILA" },
  { value: "intentarlo-odd-mami", label: "intentarlo - ODD MAMI" },
  { value: "inocencia-interrumpida-odd-mami", label: "inocencia interrumpida - ODD MAMI" },
  { value: "caramelo-mugre", label: "CARAMELO - MUGRE" },
  { value: "somos-profesionales-mugre", label: "SOMOS PROFESIONALES - MUGRE" },
  { value: "ni-tu-perra-mugre", label: "NI TU PERRA - MUGRE" },
  { value: "la-casa-de-tu-mam-kill-flora", label: "La Casa De Tu Mamá - Kill Flora" },
  { value: "quien-eras-mugre", label: "QUIEN ERAS - MUGRE" },
  { value: "ave-mara-mugre", label: "AVE MARÍA - MUGRE" },
  { value: "casino-playa-nudista", label: "Casino - Playa Nudista" },
  { value: "such-a-witch-dum-chica", label: "Such A Witch - Dum Chica" },
  { value: "casa-playa-nudista", label: "Casa - Playa Nudista" },
  { value: "lo-vers-maana-ryan", label: "Lo Verás Mañana - RYAN" },
  { value: "todo-lo-que-mora-y-los-metegoles", label: "Todo Lo Que - Mora y los Metegoles" },
  { value: "tomar-las-armas-fonso", label: "Tomar las Armas - Fonso" },
  { value: "milo-j-bzrp-music-sessions-vol-57-bizarrap", label: "Milo J: Bzrp Music Sessions, Vol. 57 - Bizarrap" },
  { value: "toy-en-el-mic-bizarrap", label: "Toy en el Mic - Bizarrap" },
  { value: "fruto-bizarrap", label: "Fruto - Bizarrap" },
  { value: "penas-de-antao-bizarrap", label: "Penas de Antaño - Bizarrap" },
  { value: "tus-vueltas-milo-j", label: "Tus Vueltas - Milo j" },
  { value: "vudu-milo-j", label: "Vudu - Milo j" },
  { value: "rincn-milo-j", label: "Rincón - Milo j" },
  { value: "domingo-milo-j", label: "Domingo - Milo j" },
  { value: "el-bolero---acstico-yami-safdie", label: "El Bolero - Acústico - Yami Safdie" },
  { value: "vainas-milo-j", label: "Vainas - Milo j" },
  { value: "no-estoy-after", label: "No Estoy - AFTER" },
  { value: "morning-milo-j", label: "MORNING - Milo j" },
  { value: "tranky-funky-trueno", label: "TRANKY FUNKY - Trueno" },
  { value: "mamichula---con-nicki-nicole-trueno", label: "Mamichula - con Nicki Nicole - Trueno" },
  { value: "solo-por-vos-trueno", label: "SOLO POR VOS - Trueno" },
  { value: "feel-me-trueno", label: "FEEL ME?? - Trueno" },
  { value: "rain-trueno", label: "Rain - Trueno" },
  { value: "bien-o-mal-trueno", label: "BIEN O MAL - Trueno" },
  { value: "dangerous-nicki-nicole", label: "Dangerous - Nicki Nicole" },
  { value: "panama-trueno", label: "PANAMA - Trueno" },
  { value: "sudaka-dante-spinetta", label: "Sudaka - Dante Spinetta" },
  { value: "buenos-aires-en-llamas-trueno", label: "BUENOS AIRES EN LLAMAS - Trueno" },
  { value: "fla-milo-j", label: "FLA - Milo j" },
  { value: "al-borde-milo-j", label: "AL BORDE - Milo j" },
  { value: "toi-hecho-milo-j", label: "TOI HECHO - Milo j" },
  { value: "rara-vez-milo-j", label: "Rara Vez - Milo j" },
  { value: "valores-del-west-milo-j", label: "Valores del West - Milo j" },
  { value: "descartable-wos", label: "DESCARTABLE - WOS" },
  { value: "morfeo-wos", label: "MORFEO - WOS" },
  { value: "culpa-wos", label: "CULPA - WOS" },
  { value: "tu-paz-milo-j", label: "Tu Paz - Milo j" },
  { value: "carencias-de-cordura-milo-j", label: "CARENCIAS DE CORDURA - Milo j" },
  { value: "paisano-de-hurlingham-divididos", label: "Paisano De Hurlingham - Divididos" },
  { value: "sbado-divididos", label: "Sábado - Divididos" },
  { value: "tanto-anteojo-divididos", label: "Tanto Anteojo - Divididos" },
  { value: "los-sueos-y-las-guerras-divididos", label: "Los Sueños y las Guerras - Divididos" },
  { value: "grgara-larga---en-vivo-divididos", label: "Gárgara Larga - En Vivo - Divididos" },
  { value: "vida-de-topos---en-vivo-divididos", label: "Vida de Topos - En Vivo - Divididos" },
  { value: "cabalgata-deportiva-divididos", label: "Cabalgata Deportiva - Divididos" },
  { value: "azulejo-divididos", label: "Azulejo - Divididos" },
  { value: "qu-tal-divididos", label: "¿Qué Tal? - Divididos" },
  { value: "la-rubia-tarada-divididos", label: "La Rubia Tarada - Divididos" },
  { value: "qu-ves-divididos", label: "¿Qué Ves? - Divididos" },
  { value: "spaghetti-del-rock-divididos", label: "Spaghetti del Rock - Divididos" },
  { value: "guanuqueando---en-vivo-divididos", label: "Guanuqueando - En Vivo - Divididos" },
  { value: "sisters-divididos", label: "Sisters - Divididos" },
  { value: "el-arriero---en-vivo-divididos", label: "El Arriero - En Vivo - Divididos" },
  { value: "san-saltarn-divididos", label: "San Saltarín - Divididos" },
  { value: "amapola-del-66-divididos", label: "Amapola del 66 - Divididos" },
  { value: "sucio-y-desprolijo-divididos", label: "Sucio y Desprolijo - Divididos" },
  { value: "crua-chan---en-vivo-sumo", label: "Crua Chan - En Vivo - Sumo" },
  { value: "cielito-lindo-divididos", label: "Cielito Lindo - Divididos" },
  { value: "rasputn-divididos", label: "Rasputín - Divididos" },
  { value: "paraguay-divididos", label: "Paraguay - Divididos" },
  { value: "sobrio-a-las-pias-quin-se-tom-todo-el-vino---en-vivo-divididos", label: "Sobrio a las Piñas / ¿Quién se Tomó Todo el Vino? - En Vivo - Divididos" },
  { value: "el-final-es-en-donde-part---en-vivo-la-renga", label: "El Final es en Donde Partí - En Vivo - La Renga" },
  { value: "ala-delta---en-vivo-divididos", label: "Ala Delta - En Vivo - Divididos" },
  { value: "medley-sumo---live-divididos", label: "Medley Sumo - Live - Divididos" },
  { value: "la-flor-azul-divididos", label: "La Flor Azul - Divididos" },
  { value: "until-i-know-panchiko", label: "Until I Know - Panchiko" },
  { value: "cherry-waves-deftones", label: "Cherry Waves - Deftones" },
  { value: "jigsaw-falling-into-place-radiohead", label: "Jigsaw Falling Into Place - Radiohead" },
  { value: "untitled-demo-1997-panchiko", label: "Untitled Demo 1997 - Panchiko" },
  { value: "all-they-wanted-panchiko", label: "All They Wanted - Panchiko" },
  { value: "knives-out-radiohead", label: "Knives Out - Radiohead" },
  { value: "failed-at-maths-panchiko", label: "Failed at Math(s) - Panchiko" },
  { value: "this-could-build-us-a-home-the-garden", label: "This Could Build Us a Home - The Garden" },
  { value: "thy-mission-the-garden", label: "Thy Mission - The Garden" },
  { value: "alison-slowdive", label: "Alison - Slowdive" },
  { value: "breakfast-sance-panchiko", label: "Breakfast Séance - Panchiko" },
  { value: "think-thats-too-wise-panchiko", label: "Think That's Too Wise - Panchiko" },
  { value: "thunder-maruja", label: "Thunder - Maruja" },
  { value: "the-tinker-maruja", label: "The Tinker - Maruja" },
  { value: "i-will-radiohead", label: "I Will - Radiohead" },
  { value: "bullet-proof-i-wish-i-was-radiohead", label: "Bullet Proof ... I Wish I Was - Radiohead" },
  { value: "bending-hectic-the-smile", label: "Bending Hectic - The Smile" },
  { value: "gwen-everest-panchiko", label: "Gwen Everest - Panchiko" },
  { value: "washer-slint", label: "Washer - Slint" },
  { value: "deathmetal-panchiko", label: "D>E>A>T>H>M>E>T>A>L - Panchiko" },
  { value: "cut-panchiko", label: "CUT - Panchiko" },
  { value: "the-smoke-the-smile", label: "The Smoke - The Smile" },
  { value: "in-between-title-fight", label: "In-Between - Title Fight" },
  { value: "donde-duele-inspira-36500-das-versin-jazz-instrumental-rafael-lechowski", label: "Donde Duele Inspira 36500 Días (Versión Jazz) [Instrumental] - Rafael Lechowski" },
  { value: "honeycomb-panchiko", label: "Honeycomb - Panchiko" },
  { value: "shelled-and-cooked-panchiko", label: "Shelled and Cooked - Panchiko" },
  { value: "macs-omelette-panchiko", label: "Mac’s Omelette - Panchiko" },
  { value: "feminine-adornments-julie", label: "feminine adornments - julie" },
  { value: "sombra-herida-canto-4", label: "Sombra Herida - Canto 4" },
  { value: "piedra-y-camino-mercedes-sosa", label: "Piedra Y Camino - Mercedes Sosa" },
  { value: "zamba-de-lozano-mercedes-sosa", label: "Zamba De Lozano - Mercedes Sosa" },
  { value: "juntito-al-fogn-los-chalchaleros", label: "Juntito al Fogón - Los Chalchaleros" },
  { value: "chacarera-de-un-triste-los-chalchaleros", label: "Chacarera de un triste - Los Chalchaleros" },
  { value: "la-atardecida-la-bruja-salguero", label: "La Atardecida - La Bruja Salguero" },
  { value: "chacarera-del-sufrido-raly-barrionuevo", label: "Chacarera del Sufrido - Raly Barrionuevo" },
  { value: "el-gordo-legero-divididos", label: "El Gordo Legüero - Divididos" },
  { value: "tonada-de-otoo-mercedes-sosa", label: "Tonada De Otoño - Mercedes Sosa" },
  { value: "pobre-mi-negra-aca-seca-trio", label: "Pobre mi negra - Aca Seca Trio" },
  { value: "alfonsina-y-el-mar-mercedes-sosa", label: "Alfonsina Y El Mar - Mercedes Sosa" },
  { value: "la-desamorada-tamara-castro", label: "La Desamorada - Tamara Castro" },
  { value: "sweet-dreams-tn-the-last-shadow-puppets", label: "Sweet Dreams, TN - The Last Shadow Puppets" },
  { value: "body-paint-arctic-monkeys", label: "Body Paint - Arctic Monkeys" },
  { value: "calm-like-you-the-last-shadow-puppets", label: "Calm Like You - The Last Shadow Puppets" },
  { value: "gas-dance-the-last-shadow-puppets", label: "Gas Dance - The Last Shadow Puppets" },
  { value: "miracle-aligner-the-last-shadow-puppets", label: "Miracle Aligner - The Last Shadow Puppets" },
  { value: "aviation-the-last-shadow-puppets", label: "Aviation - The Last Shadow Puppets" },
  { value: "standing-next-to-me-the-last-shadow-puppets", label: "Standing Next To Me - The Last Shadow Puppets" },
  { value: "in-the-heat-of-the-morning-the-last-shadow-puppets", label: "In The Heat Of The Morning - The Last Shadow Puppets" },
  { value: "my-mistakes-were-made-for-you-the-last-shadow-puppets", label: "My Mistakes Were Made For You - The Last Shadow Puppets" },
  { value: "used-to-be-my-girl-the-last-shadow-puppets", label: "Used To Be My Girl - The Last Shadow Puppets" },
  { value: "the-age-of-the-understatement-the-last-shadow-puppets", label: "The Age Of The Understatement - The Last Shadow Puppets" },
  { value: "the-element-of-surprise-the-last-shadow-puppets", label: "The Element Of Surprise - The Last Shadow Puppets" },
  { value: "the-meeting-place-the-last-shadow-puppets", label: "The Meeting Place - The Last Shadow Puppets" },
  { value: "505-arctic-monkeys", label: "505 - Arctic Monkeys" },
  { value: "shes-thunderstorms-arctic-monkeys", label: "She's Thunderstorms - Arctic Monkeys" },
  { value: "i-wanna-be-yours-arctic-monkeys", label: "I Wanna Be Yours - Arctic Monkeys" },
  { value: "stop-the-world-i-wanna-get-off-with-you-arctic-monkeys", label: "Stop The World I Wanna Get Off With You - Arctic Monkeys" },
  { value: "whyd-you-only-call-me-when-youre-high-arctic-monkeys", label: "Why'd You Only Call Me When You're High? - Arctic Monkeys" },
  { value: "do-me-a-favour-arctic-monkeys", label: "Do Me a Favour - Arctic Monkeys" },
  { value: "la-flor-azul-divididos", label: "La Flor Azul - Divididos" },
  { value: "huelga-de-amores-divididos", label: "Huelga De Amores - Divididos" },
  { value: "anda-a-lavartelos-divididos", label: "Anda A Lavartelos - Divididos" },
  { value: "el-gordo-legero-divididos", label: "El Gordo Legüero - Divididos" },
  { value: "la-amanecida---en-vivo-divididos", label: "La Amanecida - En Vivo - Divididos" },
  { value: "el-arriero---en-vivo-divididos", label: "El Arriero - En Vivo - Divididos" },
  { value: "guanuqueando---en-vivo-divididos", label: "Guanuqueando - En Vivo - Divididos" },
  { value: "vientito-de-tucumn-divididos", label: "Vientito de Tucumán - Divididos" },
  { value: "volver-ni-a-palos-divididos", label: "Volver Ni A Palos - Divididos" },
  { value: "amapola-del-66-divididos", label: "Amapola del 66 - Divididos" },
  { value: "yo-vengo-a-ofrecer-mi-corazon-fito-paez", label: "Yo Vengo A Ofrecer Mi Corazon - Fito Paez" },
  { value: "ortega-y-gases-divididos", label: "Ortega Y Gases - Divididos" },
  { value: "haciendo-cosas-raras-divididos", label: "Haciendo Cosas Raras - Divididos" },
  { value: "una-piba-con-la-remera-de-greenpeace-patricio-rey-y-sus-redonditos-de-ricota", label: "Una Piba Con la Remera de Greenpeace - Patricio Rey y sus Redonditos de Ricota" },
  { value: "como-el-viento-voy-a-ver-pescado-rabioso", label: "Como el Viento Voy a Ver - Pescado Rabioso" },
  { value: "spaghetti-del-rock-divididos", label: "Spaghetti del Rock - Divididos" },
  { value: "rutas-argentinas-almendra", label: "Rutas Argentinas - Almendra" },
  { value: "zafar-la-vela-puerca", label: "Zafar - La Vela Puerca" },
  { value: "al-atardecer-los-piojos", label: "Al Atardecer - Los Piojos" },
  { value: "toco-y-me-voy-bersuit-vergarabat", label: "Toco Y Me Voy - Bersuit Vergarabat" },
  { value: "el-farolito-los-piojos", label: "El Farolito - Los Piojos" },
  { value: "como-un-cuento-divididos", label: "Como un Cuento - Divididos" },
  { value: "dame-un-limn-divididos", label: "Dame Un Limón - Divididos" },
  { value: "nene-de-antes-divididos", label: "Nene de Antes - Divididos" },
  { value: "par-mil-divididos", label: "Par Mil - Divididos" },
  { value: "seor-kioskero-intoxicados", label: "Señor Kioskero - Intoxicados" },
  { value: "despirtate-nena-pescado-rabioso", label: "Despiértate Nena - Pescado Rabioso" },
  { value: "civilizacin-los-piojos", label: "Civilización - Los Piojos" },
  { value: "murguita-del-sur-bersuit-vergarabat", label: "Murguita Del Sur - Bersuit Vergarabat" },
  { value: "tu-amor-charly-garca", label: "Tu Amor - Charly García" },
  { value: "ser-las-pelotas", label: "Será - Las Pelotas" },
  { value: "sucio-y-desprolijo-pappos-blues", label: "Sucio y Desprolijo - Pappo's Blues" },
  { value: "raros-peinados-nuevos-charly-garca", label: "Raros Peinados Nuevos - Charly García" },
  { value: "desconexin-sideral-bersuit-vergarabat", label: "Desconexión Sideral - Bersuit Vergarabat" },
  { value: "tan-solo-los-piojos", label: "Tan Solo - Los Piojos" },
  { value: "los-viejos-vinagres-sumo", label: "Los Viejos Vinagres - Sumo" },
  { value: "lisa-gustavo-cerati", label: "Lisa - Gustavo Cerati" },
  { value: "cactus-gustavo-cerati", label: "Cactus - Gustavo Cerati" },
  { value: "la-soledad-bersuit-vergarabat", label: "La Soledad - Bersuit Vergarabat" },
  { value: "campanas-en-la-noche-los-tipitos", label: "Campanas en la Noche - Los Tipitos" },
  { value: "nunca-quise-intoxicados", label: "Nunca quise - Intoxicados" },
  { value: "sigue-girando-ratones-paranoicos", label: "Sigue Girando - Ratones Paranoicos" },
  { value: "el-38-divididos", label: "El 38 - Divididos" },
  { value: "lamento-boliviano-los-enanitos-verdes", label: "Lamento Boliviano - Los Enanitos Verdes" },
  { value: "giros-fito-paez", label: "Giros - Fito Paez" },
  { value: "estar-los-visitantes", label: "Estaré - Los Visitantes" },
  { value: "pi-pa-pu-los-visitantes", label: "Pi-Pa-Pu - Los Visitantes" },
  { value: "ella-vendr---remastered-don-cornelio-y-la-zona", label: "Ella Vendrá - Remastered - Don Cornelio Y La Zona" },
  { value: "gol-de-mujer-divididos", label: "Gol de Mujer - Divididos" },
  { value: "salgan-al-sol-divididos", label: "Salgan al Sol - Divididos" },
  { value: "noche-azul-los-visitantes", label: "Noche Azul - Los Visitantes" },
  { value: "playas-oscuras-los-visitantes", label: "Playas Oscuras - Los Visitantes" },
  { value: "el-pibe-de-los-astilleros-patricio-rey-y-sus-redonditos-de-ricota", label: "El Pibe de los Astilleros - Patricio Rey y sus Redonditos de Ricota" },
  { value: "me-matan-limn-patricio-rey-y-sus-redonditos-de-ricota", label: "Me Matan Limón! - Patricio Rey y sus Redonditos de Ricota" },
  { value: "qu-ves-divididos", label: "¿Qué Ves? - Divididos" },
  { value: "esa-estrella-era-mi-lujo-patricio-rey-y-sus-redonditos-de-ricota", label: "Esa Estrella Era Mi Lujo - Patricio Rey y sus Redonditos de Ricota" },
  { value: "paisano-de-hurlingham-divididos", label: "Paisano De Hurlingham - Divididos" },
  { value: "sbado-divididos", label: "Sábado - Divididos" },
  { value: "la-api-de-mam-divididos", label: "La Ñapi de Mamá - Divididos" },
  { value: "vida-de-topos-divididos", label: "Vida de Topos - Divididos" },
  { value: "vuelos-bersuit-vergarabat", label: "Vuelos - Bersuit Vergarabat" },
  { value: "tazas-de-t-chino---remastered-don-cornelio-y-la-zona", label: "Tazas De Té Chino - Remastered - Don Cornelio Y La Zona" },
  { value: "cenizas-y-diamantes---remastered-don-cornelio-y-la-zona", label: "Cenizas y Diamantes - Remastered - Don Cornelio Y La Zona" },
  { value: "dice-la-vela-puerca", label: "Dice - La Vela Puerca" },
  { value: "un-pacto---live-in-buenos-aires-2001-bersuit-vergarabat", label: "Un Pacto - Live In Buenos Aires / 2001 - Bersuit Vergarabat" },
  { value: "no-llores-por-m-argentina-en-vivo-ser-girn", label: "No Llores Por Mí, Argentina (En Vivo) - Serú Girán" },
  { value: "popotitos---live-ser-girn", label: "Popotitos - Live - Serú Girán" },
  { value: "plateado-sobre-plateado-huellas-en-el-mar-charly-garca", label: "Plateado Sobre Plateado (Huellas En El Mar) - Charly García" },
  { value: "cerca-de-la-revolucion-charly-garca", label: "Cerca De La Revolucion - Charly García" },
  { value: "hipercandombe-la-maquina-de-hacer-pjaros", label: "Hipercandombe - La Maquina De Hacer Pájaros" },
  { value: "muerto-a-laburar-divididos", label: "Muerto a Laburar - Divididos" },
  { value: "el-viejo-la-vela-puerca", label: "El Viejo - La Vela Puerca" },
  { value: "la-grasa-de-las-capitales---2019-remasterizado-ser-girn", label: "La Grasa de las Capitales - 2019 Remasterizado - Serú Girán" },
  { value: "dancing-barefoot-patti-smith", label: "Dancing Barefoot - Patti Smith" },
  { value: "deceptacon-le-tigre", label: "Deceptacon - Le Tigre" },
  { value: "because-the-night-patti-smith", label: "Because the Night - Patti Smith" },
  { value: "whats-yr-take-on-cassavetes-le-tigre", label: "What's Yr Take On Cassavetes? - Le Tigre" },
  { value: "hot-topic-le-tigre", label: "Hot Topic - Le Tigre" },
  { value: "the-passenger-siouxsie-and-the-banshees", label: "The Passenger - Siouxsie and the Banshees" },
  { value: "wet-dazey-and-the-scouts", label: "Wet - Dazey and the Scouts" },
  { value: "second-skin-the-gits", label: "Second Skin - The Gits" },
  { value: "rebel-girl-bikini-kill", label: "Rebel Girl - Bikini Kill" },
  { value: "cherry-bomb-the-runaways", label: "Cherry Bomb - The Runaways" },
  { value: "maggot-slutever", label: "Maggot - Slutever" },
  { value: "galaxy-voiid", label: "Galaxy - Voiid" },
  { value: "romantic-mannequin-pussy", label: "Romantic - Mannequin Pussy" },
  { value: "pretend-were-dead-l7", label: "Pretend We're Dead - L7" },
  { value: "form-of-luxury-drahla", label: "Form Of Luxury - Drahla" },
  { value: "107-team-dresch", label: "107 - Team Dresch" },
  { value: "remember-who-you-are-team-dresch", label: "Remember Who You Are - Team Dresch" },
  { value: "kill-yr-idols-sonic-youth", label: "Kill Yr. Idols - Sonic Youth" },
  { value: "jenny-sleater-kinney", label: "Jenny - Sleater-Kinney" },
  { value: "violet-hole", label: "Violet - Hole" },
  { value: "the-bad-thing-arctic-monkeys", label: "The Bad Thing - Arctic Monkeys" },
  { value: "i-bet-you-look-good-on-the-dancefloor-arctic-monkeys", label: "I Bet You Look Good On The Dancefloor - Arctic Monkeys" },
  { value: "fake-tales-of-san-francisco-arctic-monkeys", label: "Fake Tales Of San Francisco - Arctic Monkeys" },
  { value: "brick-by-brick-arctic-monkeys", label: "Brick By Brick - Arctic Monkeys" },
  { value: "dont-sit-down-cause-ive-moved-your-chair-arctic-monkeys", label: "Don't Sit Down 'Cause I've Moved Your Chair - Arctic Monkeys" },
  { value: "library-pictures-arctic-monkeys", label: "Library Pictures - Arctic Monkeys" },
  { value: "r-u-mine-arctic-monkeys", label: "R U Mine? - Arctic Monkeys" },
  { value: "arabella-arctic-monkeys", label: "Arabella - Arctic Monkeys" },
  { value: "whyd-you-only-call-me-when-youre-high-arctic-monkeys", label: "Why'd You Only Call Me When You're High? - Arctic Monkeys" },
  { value: "snap-out-of-it-arctic-monkeys", label: "Snap Out of It - Arctic Monkeys" },
  { value: "knee-socks-arctic-monkeys", label: "Knee Socks - Arctic Monkeys" },
  { value: "settle-for-a-draw-arctic-monkeys", label: "Settle For A Draw - Arctic Monkeys" },
  { value: "7-arctic-monkeys", label: "7 - Arctic Monkeys" },
  { value: "cigarette-smoker-fiona-arctic-monkeys", label: "Cigarette Smoker Fiona - Arctic Monkeys" },
  { value: "da-frame-2r-arctic-monkeys", label: "Da Frame 2R - Arctic Monkeys" },
  { value: "red-right-hand-arctic-monkeys", label: "Red Right Hand - Arctic Monkeys" },
  { value: "catapult-arctic-monkeys", label: "Catapult - Arctic Monkeys" },
  { value: "joining-the-dots-arctic-monkeys", label: "Joining The Dots - Arctic Monkeys" },
  { value: "the-afternoons-hat-arctic-monkeys", label: "The Afternoon's Hat - Arctic Monkeys" },
  { value: "evil-twin-arctic-monkeys", label: "Evil Twin - Arctic Monkeys" },
  { value: "stop-the-world-i-wanna-get-off-with-you-arctic-monkeys", label: "Stop The World I Wanna Get Off With You - Arctic Monkeys" },
  { value: "dancing-shoes-arctic-monkeys", label: "Dancing Shoes - Arctic Monkeys" },
  { value: "you-probably-couldnt-see-for-the-lights-but-you-were-staring-straight-at-me-arctic-monkeys", label: "You Probably Couldn't See For The Lights But You Were Staring Straight At Me - Arctic Monkeys" },
  { value: "still-take-you-home-arctic-monkeys", label: "Still Take You Home - Arctic Monkeys" },
  { value: "red-light-indicates-doors-are-secured-arctic-monkeys", label: "Red Light Indicates Doors Are Secured - Arctic Monkeys" },
  { value: "perhaps-vampires-is-a-bit-strong-but-arctic-monkeys", label: "Perhaps Vampires Is A Bit Strong But… - Arctic Monkeys" },
  { value: "from-the-ritz-to-the-rubble-arctic-monkeys", label: "From The Ritz To The Rubble - Arctic Monkeys" },
  { value: "teddy-picker-arctic-monkeys", label: "Teddy Picker - Arctic Monkeys" },
  { value: "d-is-for-dangerous-arctic-monkeys", label: "D is for Dangerous - Arctic Monkeys" },
  { value: "balaclava-arctic-monkeys", label: "Balaclava - Arctic Monkeys" },
  { value: "fluorescent-adolescent-arctic-monkeys", label: "Fluorescent Adolescent - Arctic Monkeys" },
  { value: "do-me-a-favour-arctic-monkeys", label: "Do Me a Favour - Arctic Monkeys" },
  { value: "if-you-were-there-beware-arctic-monkeys", label: "If You Were There, Beware - Arctic Monkeys" },
  { value: "my-propeller-arctic-monkeys", label: "My Propeller - Arctic Monkeys" },
  { value: "dangerous-animals-arctic-monkeys", label: "Dangerous Animals - Arctic Monkeys" },
  { value: "potion-approaching-arctic-monkeys", label: "Potion Approaching - Arctic Monkeys" },
  { value: "pretty-visitors-arctic-monkeys", label: "Pretty Visitors - Arctic Monkeys" },
  { value: "black-treacle-arctic-monkeys", label: "Black Treacle - Arctic Monkeys" },
  { value: "all-my-own-stunts-arctic-monkeys", label: "All My Own Stunts - Arctic Monkeys" },
  { value: "suck-it-and-see-arctic-monkeys", label: "Suck It and See - Arctic Monkeys" },
  { value: "do-i-wanna-know-arctic-monkeys", label: "Do I Wanna Know? - Arctic Monkeys" },
  { value: "i-want-it-all-arctic-monkeys", label: "I Want It All - Arctic Monkeys" },
  { value: "one-for-the-road-arctic-monkeys", label: "One for the Road - Arctic Monkeys" },
  { value: "fireside-arctic-monkeys", label: "Fireside - Arctic Monkeys" },
  { value: "tranquility-base-hotel-casino-arctic-monkeys", label: "Tranquility Base Hotel & Casino - Arctic Monkeys" },
  { value: "four-out-of-five-arctic-monkeys", label: "Four Out Of Five - Arctic Monkeys" },
  { value: "batphone-arctic-monkeys", label: "Batphone - Arctic Monkeys" },
  { value: "bigger-boys-and-stolen-sweethearts-arctic-monkeys", label: "Bigger Boys and Stolen Sweethearts - Arctic Monkeys" },
  { value: "who-the-fuck-are-arctic-monkeys-arctic-monkeys", label: "Who The Fuck Are Arctic Monkeys? - Arctic Monkeys" },
  { value: "temptation-greets-you-like-your-naughty-friend-arctic-monkeys", label: "Temptation Greets You Like Your Naughty Friend - Arctic Monkeys" },
  { value: "plastic-tramp-arctic-monkeys", label: "Plastic Tramp - Arctic Monkeys" },
  { value: "nettles-arctic-monkeys", label: "Nettles - Arctic Monkeys" },
  { value: "bad-woman-arctic-monkeys", label: "Bad Woman - Arctic Monkeys" },
  { value: "the-blond-o-sonic-shimmer-trap-arctic-monkeys", label: "The Blond-O-Sonic Shimmer Trap - Arctic Monkeys" },
  { value: "idst-arctic-monkeys", label: "I.D.S.T. - Arctic Monkeys" },
  { value: "you-and-i-richard-hawley", label: "You and I - Richard Hawley" },
  { value: "little-illusion-machine-wirral-riddler-miles-kane-and-the-death-ramps", label: "Little Illusion Machine (Wirral Riddler) - Miles Kane and the Death Ramps" },
  { value: "2013-arctic-monkeys", label: "2013 - Arctic Monkeys" },
  { value: "body-paint-arctic-monkeys", label: "Body Paint - Arctic Monkeys" },
  { value: "crying-lightning-arctic-monkeys", label: "Crying Lightning - Arctic Monkeys" },
  { value: "505-arctic-monkeys", label: "505 - Arctic Monkeys" },
  { value: "too-much-to-ask-arctic-monkeys", label: "Too Much To Ask - Arctic Monkeys" },
  { value: "old-yellow-bricks-arctic-monkeys", label: "Old Yellow Bricks - Arctic Monkeys" },
  { value: "riot-van-arctic-monkeys", label: "Riot Van - Arctic Monkeys" },
  { value: "mardy-bum-arctic-monkeys", label: "Mardy Bum - Arctic Monkeys" },
  { value: "when-the-sun-goes-down-arctic-monkeys", label: "When The Sun Goes Down - Arctic Monkeys" },
  { value: "a-certain-romance-arctic-monkeys", label: "A Certain Romance - Arctic Monkeys" },
  { value: "only-ones-who-know-arctic-monkeys", label: "Only Ones Who Know - Arctic Monkeys" },
  { value: "505-arctic-monkeys", label: "505 - Arctic Monkeys" },
  { value: "secret-door-arctic-monkeys", label: "Secret Door - Arctic Monkeys" },
  { value: "fire-and-the-thud-arctic-monkeys", label: "Fire And The Thud - Arctic Monkeys" },
  { value: "cornerstone-arctic-monkeys", label: "Cornerstone - Arctic Monkeys" },
  { value: "dance-little-liar-arctic-monkeys", label: "Dance Little Liar - Arctic Monkeys" },
  { value: "shes-thunderstorms-arctic-monkeys", label: "She's Thunderstorms - Arctic Monkeys" },
  { value: "the-hellcat-spangled-shalalala-arctic-monkeys", label: "The Hellcat Spangled Shalalala - Arctic Monkeys" },
  { value: "reckless-serenade-arctic-monkeys", label: "Reckless Serenade - Arctic Monkeys" },
  { value: "piledriver-waltz-arctic-monkeys", label: "Piledriver Waltz - Arctic Monkeys" },
  { value: "love-is-a-laserquest-arctic-monkeys", label: "Love is a Laserquest - Arctic Monkeys" },
  { value: "thats-where-youre-wrong-arctic-monkeys", label: "That's Where You're Wrong - Arctic Monkeys" },
  { value: "no1-party-anthem-arctic-monkeys", label: "No.1 Party Anthem - Arctic Monkeys" },
  { value: "mad-sounds-arctic-monkeys", label: "Mad Sounds - Arctic Monkeys" },
  { value: "i-wanna-be-yours-arctic-monkeys", label: "I Wanna Be Yours - Arctic Monkeys" },
  { value: "star-treatment-arctic-monkeys", label: "Star Treatment - Arctic Monkeys" },
  { value: "the-ultracheese-arctic-monkeys", label: "The Ultracheese - Arctic Monkeys" },
  { value: "thered-better-be-a-mirrorball-arctic-monkeys", label: "There’d Better Be A Mirrorball - Arctic Monkeys" },
  { value: "despair-in-the-departure-lounge-arctic-monkeys", label: "Despair In The Departure Lounge - Arctic Monkeys" },
  { value: "no-buses-arctic-monkeys", label: "No Buses - Arctic Monkeys" },
  { value: "baby-im-yours-arctic-monkeys", label: "Baby I'm Yours - Arctic Monkeys" },
  { value: "the-bakery-arctic-monkeys", label: "The Bakery - Arctic Monkeys" },
  { value: "joining-the-dots-arctic-monkeys", label: "Joining The Dots - Arctic Monkeys" },
  { value: "stop-the-world-i-wanna-get-off-with-you-arctic-monkeys", label: "Stop The World I Wanna Get Off With You - Arctic Monkeys" },
  { value: "anyways-arctic-monkeys", label: "Anyways - Arctic Monkeys" },
  { value: "body-paint-arctic-monkeys", label: "Body Paint - Arctic Monkeys" },
  { value: "risa-babasonicos", label: "Risa - Babasonicos" },
  { value: "putita-babasonicos", label: "Putita - Babasonicos" },
  { value: "y-qu-babasonicos", label: "Y qué - Babasonicos" },
  { value: "irresponsables-babasonicos", label: "Irresponsables - Babasonicos" },
  { value: "el-loco-babasonicos", label: "El Loco - Babasonicos" },
  { value: "los-calientes-babasonicos", label: "Los Calientes - Babasonicos" },
  { value: "fizz-babasonicos", label: "Fizz - Babasonicos" },
  { value: "como-eran-las-cosas-babasonicos", label: "Como Eran Las Cosas - Babasonicos" },
  { value: "rub-babasonicos", label: "Rubí - Babasonicos" },
  { value: "arbol-palmera-babasonicos", label: "Arbol Palmera - Babasonicos" },
  { value: "valle-de-valium-babasonicos", label: "Valle de Valium - Babasonicos" },
  { value: "oportunidad-babasonicos", label: "Oportunidad - Babasonicos" },
  { value: "pijamas-babasonicos", label: "Pijamas - Babasonicos" },
  { value: "escamas-babasonicos", label: "Escamas - Babasonicos" },
  { value: "carismtico-babasonicos", label: "Carismático - Babasonicos" },
  { value: "celofn-babasonicos", label: "Celofán - Babasonicos" },
  { value: "bestia-pequea-babasonicos", label: "Bestia Pequeña - Babasonicos" },
  { value: "microdancing-babasonicos", label: "Microdancing - Babasonicos" },
  { value: "yegua-babasonicos", label: "Yegua - Babasonicos" },
  { value: "cretino-babasonicos", label: "Cretino - Babasonicos" },
  { value: "los-burcratas-del-amor-babasonicos", label: "Los Burócratas del Amor - Babasonicos" },
  { value: "orfeo-babasonicos", label: "Orfeo - Babasonicos" },
  { value: "estoy-rabioso-babasonicos", label: "Estoy Rabioso - Babasonicos" },
  { value: "fiesta-popular-babasonicos", label: "Fiesta Popular - Babasonicos" },
  { value: "cuello-rojo-babasonicos", label: "Cuello Rojo - Babasonicos" },
  { value: "bye-bye-babasonicos", label: "Bye Bye - Babasonicos" },
  { value: "mimos-son-mimos-babasonicos", label: "Mimos Son Mimos - Babasonicos" },
  { value: "paradoja-babasonicos", label: "Paradoja - Babasonicos" },
  { value: "la-lanza-babasonicos", label: "La Lanza - Babasonicos" },
  { value: "microdancing-babasonicos", label: "Microdancing - Babasonicos" },
  { value: "ever-fallen-in-love-with-someone-you-shouldntve---1996-remastered-version-buzzcocks", label: "Ever Fallen in Love (With Someone You Shouldn't've?) - 1996 Remastered Version - Buzzcocks" },
  { value: "waiting-room-fugazi", label: "Waiting Room - Fugazi" },
  { value: "disorder---2007-remaster-joy-division", label: "Disorder - 2007 Remaster - Joy Division" },
  { value: "teen-age-riot-album-version-sonic-youth", label: "Teen Age Riot (Album Version) - Sonic Youth" },
  { value: "purr-sonic-youth", label: "Purr - Sonic Youth" },
  { value: "incinerate-sonic-youth", label: "Incinerate - Sonic Youth" },
  { value: "bull-in-the-heather-sonic-youth", label: "Bull In The Heather - Sonic Youth" },
  { value: "kill-yr-idols-sonic-youth", label: "Kill Yr. Idols - Sonic Youth" },
  { value: "schizophrenia-sonic-youth", label: "Schizophrenia - Sonic Youth" },
  { value: "murdered-out-kim-gordon", label: "Murdered Out - Kim Gordon" },
  { value: "spanish-bombs---remastered-the-clash", label: "Spanish Bombs - Remastered - The Clash" },
  { value: "all-the-young-punks-new-boots-and-contracts---remastered-the-clash", label: "All the Young Punks (New Boots and Contracts) - Remastered - The Clash" },
  { value: "damaged-goods-gang-of-four", label: "Damaged Goods - Gang Of Four" },
  { value: "deans-dream-the-dead-milkmen", label: "Dean's Dream - The Dead Milkmen" },
  { value: "death-valley-69-w-lydia-lunch-sonic-youth", label: "Death Valley '69 (W/ Lydia Lunch) - Sonic Youth" },
  { value: "marilyn-moore-sonic-youth", label: "Marilyn Moore - Sonic Youth" },
  { value: "pretend-were-dead-l7", label: "Pretend We're Dead - L7" },
  { value: "little-trouble-girl-sonic-youth", label: "Little Trouble Girl - Sonic Youth" },
  { value: "vile-voiid", label: "Vile - Voiid" },
  { value: "cattywampus-destroy-boys", label: "Cattywampus - Destroy Boys" },
  { value: "bizarre-love-triangle---2011-total-version-shep-pettibone-7-remix-new-order", label: "Bizarre Love Triangle - 2011 Total Version; Shep Pettibone 7 Remix - New Order" },
  { value: "warsaw---2010-remaster-joy-division", label: "Warsaw - 2010 Remaster - Joy Division" },
  { value: "molchat-doma", label: "Судно (Борис Рижий) - Molchat Doma" },
  { value: "debaser-pixies", label: "Debaser - Pixies" },
  { value: "the-process-chastity-belt", label: "The Process - Chastity Belt" },
  { value: "fences-destroy-boys", label: "Fences - Destroy Boys" },
  { value: "celebrity-skin-hole", label: "Celebrity Skin - Hole" },
  { value: "some-velvet-morning-slowdive", label: "Some Velvet Morning - Slowdive" },
  { value: "kissability-live-sonic-youth", label: "Kissability (Live) - Sonic Youth" },
  { value: "cross-the-breeze-live-sonic-youth", label: "'Cross the Breeze (Live) - Sonic Youth" },
  { value: "teen-age-riot-live-sonic-youth", label: "Teen Age Riot (Live) - Sonic Youth" },
  { value: "gary-gilmores-eyes-the-adverts", label: "Gary Gilmore's Eyes - The Adverts" },
  { value: "lets-go-to-bed-the-cure", label: "Let's Go To Bed - The Cure" },
  { value: "the-passenger-siouxsie-and-the-banshees", label: "The Passenger - Siouxsie and the Banshees" },
  { value: "electioneering-radiohead", label: "Electioneering - Radiohead" },
  { value: "1312-pussy-riot", label: "1312 - Pussy Riot" },
]

import { useRouter } from "next/navigation"

// ... (imports remain the same)

export default function VinylHero({
  title = "SAMPLE",
  titleColor = "text-white",
  videoId = "dQw4w9WgXcQ",
  showInput = true,
  linkText,
  linkUrl,
  data,
}: VinylHeroProps) {
  const [open, setOpen] = useState(false)
  const [value, setValue] = useState("")
  const router = useRouter()

  const [attempts, setAttempts] = useState<string[]>([])

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()

    if (!data) return

    const selectedSong = availableSongs.find((song) => song.value === value)
    const expectedLabel = `${data.Answer.song_title} - ${data.Answer.artist_name}`

    if (selectedSong && selectedSong.label === expectedLabel) {
      router.push("/exito")
    } else {
      // Add to attempts if not already there
      if (selectedSong && !attempts.includes(selectedSong.label)) {
        setAttempts((prev) => [...prev, selectedSong.label])
      }
      setValue("") // Clear input
    }
  }

  const getYoutubeId = (url: string | null | undefined) => {
    if (!url) return ""
    const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]*).*/
    const match = url.match(regExp)
    return match && match[2].length === 11 ? match[2] : url
  }

  const embedId = getYoutubeId(videoId)

  return (
    <div className="relative min-h-screen overflow-hidden bg-background">
      <div className="absolute top-0 left-0 right-0 z-20 flex items-center justify-between px-8 py-6">
        <h1 className={`text-4xl font-bold tracking-wider ${titleColor}`}>{title}</h1>
        <Button variant="ghost" size="icon" className="h-10 w-10 text-white hover:bg-white/10 border border-white/20">
          <HelpCircle className="h-5 w-5" />
          <span className="sr-only">Ayuda</span>
        </Button>
      </div>

      {/* Left Half Vinyl */}
      <div className="absolute left-0 top-1/2 -translate-y-1/2 -translate-x-1/2 w-[600px] h-[600px] pointer-events-none">
        <div className="absolute inset-0 rounded-full bg-gradient-to-br from-gray-900 via-gray-800 to-black">
          {/* Grooves effect */}
          {[...Array(25)].map((_, i) => (
            <div
              key={i}
              className="absolute rounded-full border border-gray-700/20"
              style={{
                inset: `${i * 4}px`,
              }}
            />
          ))}

          {/* Center label */}
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-40 h-40 rounded-full bg-gray-100 flex items-center justify-center shadow-xl">
            <div className="w-12 h-12 rounded-full bg-background border-4 border-gray-900" />
          </div>
        </div>
      </div>

      {/* Right Half Vinyl */}
      <div className="absolute right-0 top-1/2 -translate-y-1/2 translate-x-1/2 w-[600px] h-[600px] pointer-events-none">
        <div className="absolute inset-0 rounded-full bg-gradient-to-bl from-gray-900 via-gray-800 to-black">
          {/* Grooves effect */}
          {[...Array(25)].map((_, i) => (
            <div
              key={i}
              className="absolute rounded-full border border-gray-700/20"
              style={{
                inset: `${i * 4}px`,
              }}
            />
          ))}

          {/* Center label */}
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-40 h-40 rounded-full bg-gray-100 flex items-center justify-center shadow-xl">
            <div className="w-12 h-12 rounded-full bg-background border-4 border-gray-900" />
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="relative z-10 min-h-screen flex items-center justify-center px-4 py-12">
        <div className="w-full max-w-4xl">
          <div className="space-y-8">
            {/* YouTube Video Player */}
            <div className="w-full aspect-video rounded-lg overflow-hidden border-2 border-gray-800 shadow-2xl bg-black">
              <iframe
                className="w-full h-full"
                src={`https://www.youtube.com/embed/${embedId}`}
                title="YouTube video player"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
              />
            </div>

            {showInput ? (
              <form onSubmit={handleSubmit} className="flex gap-3 max-w-2xl mx-auto">
                <Popover open={open} onOpenChange={setOpen}>
                  <PopoverTrigger asChild>
                    <Button
                      variant="outline"
                      role="combobox"
                      aria-expanded={open}
                      className="flex-1 h-12 justify-between bg-card border-border text-foreground"
                    >
                      {value ? availableSongs.find((song) => song.value === value)?.label : "Selecciona una canción..."}
                      <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-[600px] p-0">
                    <Command>
                      <CommandInput placeholder="Buscar canción..." />
                      <CommandList>
                        <CommandEmpty>Esa canción no está en la base de datos</CommandEmpty>
                        <CommandGroup>
                          {availableSongs.map((song) => (
                            <CommandItem
                              key={song.value}
                              value={song.value}
                              onSelect={(currentValue: string) => {
                                setValue(currentValue === value ? "" : currentValue)
                                setOpen(false)
                              }}
                            >
                              <Check
                                className={cn("mr-2 h-4 w-4", value === song.value ? "opacity-100" : "opacity-0")}
                              />
                              {song.label}
                            </CommandItem>
                          ))}
                        </CommandGroup>
                      </CommandList>
                    </Command>
                  </PopoverContent>
                </Popover>
                <Button type="submit" size="icon" className="h-12 w-12 bg-gray-900 hover:bg-gray-800 text-white">
                  <ArrowRight className="h-5 w-5" />
                  <span className="sr-only">Enviar</span>
                </Button>
              </form>
            ) : (
              linkText &&
              linkUrl && (
                <div className="text-center">
                  <a
                    href={linkUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-2 text-lg font-medium hover:underline text-foreground"
                  >
                    {linkText}
                    <ArrowRight className="h-5 w-5" />
                  </a>
                </div>
              )
            )}

            {/* Incorrect Attempts List */}
            {attempts.length > 0 && showInput && (
              <div className="mt-8 max-w-2xl mx-auto">
                <h3 className="text-red-500 font-semibold mb-4 text-center">Intentos fallidos:</h3>
                <ul className="space-y-2">
                  {attempts.map((attempt, index) => (
                    <li key={index} className="bg-red-500/10 border border-red-500/20 rounded-md p-3 text-red-200 flex items-center gap-2">
                      <span className="text-red-500">✕</span> {attempt}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
